// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash, password_reset_required, password_changed_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    CASE WHEN $3::text IS NULL THEN NULL ELSE now() END
)
RETURNING id, email, display_name, password_hash, disabled_at, created_at, updated_at, password_changed_at, password_reset_required
`

type CreateUserParams struct {
	Email                 string  `json:"email"`
	DisplayName           string  `json:"display_name"`
	PasswordHash          *string `json:"password_hash"`
	PasswordResetRequired bool    `json:"password_reset_required"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.PasswordResetRequired,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordChangedAt,
		&i.PasswordResetRequired,
	)
	return i, err
}

const disableUser = `-- name: DisableUser :execrows
UPDATE users SET disabled_at = $1, updated_at = now() WHERE id = $2 AND disabled_at IS NULL
`

type DisableUserParams struct {
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	ID         int64              `json:"id"`
}

func (q *Queries) DisableUser(ctx context.Context, arg DisableUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableUser, arg.DisabledAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enableUser = `-- name: EnableUser :execrows
UPDATE users SET disabled_at = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) EnableUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, enableUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, password_hash, disabled_at, created_at, updated_at, password_changed_at, password_reset_required FROM users
WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordChangedAt,
		&i.PasswordResetRequired,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, password_hash, disabled_at, created_at, updated_at, password_changed_at, password_reset_required FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordChangedAt,
		&i.PasswordResetRequired,
	)
	return i, err
}

const revokeActiveSessionsForUser = `-- name: RevokeActiveSessionsForUser :execrows
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) RevokeActiveSessionsForUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActiveSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1
    AND revoked_at IS NULL
    AND expires_at > now()
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserLifecycle = `-- name: UpdateUserLifecycle :one
UPDATE users
SET
    display_name = COALESCE($1, display_name),
    disabled_at = CASE
        WHEN $2::boolean IS NULL THEN disabled_at
        WHEN $2::boolean THEN COALESCE(disabled_at, $3)
        ELSE NULL
    END,
    updated_at = $3
WHERE id = $4
RETURNING id, email, display_name, password_hash, disabled_at, created_at, updated_at, password_changed_at, password_reset_required
`

type UpdateUserLifecycleParams struct {
	DisplayName *string            `json:"display_name"`
	Disabled    *bool              `json:"disabled"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          int64              `json:"id"`
}

func (q *Queries) UpdateUserLifecycle(ctx context.Context, arg UpdateUserLifecycleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLifecycle,
		arg.DisplayName,
		arg.Disabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordChangedAt,
		&i.PasswordResetRequired,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $1,
    password_changed_at = now(),
    password_reset_required = false,
    updated_at = now()
WHERE id = $2
RETURNING id, email, display_name, password_hash, disabled_at, created_at, updated_at, password_changed_at, password_reset_required
`

type UpdateUserPasswordParams struct {
	PasswordHash *string `json:"password_hash"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordChangedAt,
		&i.PasswordResetRequired,
	)
	return i, err
}
