// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUserAccess struct {
	UserID         int64              `json:"user_id"`
	Email          string             `json:"email"`
	DisplayName    string             `json:"display_name"`
	DisabledAt     pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	MembershipID   int64              `json:"membership_id"`
	Role           string             `json:"role"`
	OrganisationID *int64             `json:"organisation_id"`
	District       *string            `json:"district"`
	LastSeenAt     interface{}        `json:"last_seen_at"`
}

type AuditEvent struct {
	ID             int64              `json:"id"`
	ExternalID     *string            `json:"external_id"`
	ClinicID       *string            `json:"clinic_id"`
	ActorName      *string            `json:"actor_name"`
	EventType      string             `json:"event_type"`
	Summary        string             `json:"summary"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ActorUserID    *int64             `json:"actor_user_id"`
	ActorRole      *string            `json:"actor_role"`
	OrganisationID *int64             `json:"organisation_id"`
	EntityType     *string            `json:"entity_type"`
	EntityID       *string            `json:"entity_id"`
	Metadata       []byte             `json:"metadata"`
}

type Clinic struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	FacilityCode       string             `json:"facility_code"`
	Province           string             `json:"province"`
	District           string             `json:"district"`
	Latitude           pgtype.Numeric     `json:"latitude"`
	Longitude          pgtype.Numeric     `json:"longitude"`
	OperatingHours     *string            `json:"operating_hours"`
	FacilityType       string             `json:"facility_type"`
	VerificationStatus string             `json:"verification_status"`
	LastVerifiedAt     pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ClinicService struct {
	ClinicID            string             `json:"clinic_id"`
	ServiceName         string             `json:"service_name"`
	CurrentAvailability string             `json:"current_availability"`
	ConfidenceScore     pgtype.Numeric     `json:"confidence_score"`
	LastVerifiedAt      pgtype.Timestamptz `json:"last_verified_at"`
}

type CurrentStatus struct {
	ClinicID        string             `json:"clinic_id"`
	Status          string             `json:"status"`
	Reason          *string            `json:"reason"`
	Freshness       string             `json:"freshness"`
	LastReportedAt  pgtype.Timestamptz `json:"last_reported_at"`
	ReporterName    *string            `json:"reporter_name"`
	Source          *string            `json:"source"`
	StaffPressure   *string            `json:"staff_pressure"`
	StockPressure   *string            `json:"stock_pressure"`
	QueuePressure   *string            `json:"queue_pressure"`
	ConfidenceScore pgtype.Numeric     `json:"confidence_score"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type IntegrationStatusCheck struct {
	ID             int64              `json:"id"`
	OrganisationID *int64             `json:"organisation_id"`
	CheckName      string             `json:"check_name"`
	Status         string             `json:"status"`
	Summary        string             `json:"summary"`
	Metadata       []byte             `json:"metadata"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
}

type Organisation struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganisationMembership struct {
	ID             int64              `json:"id"`
	OrganisationID *int64             `json:"organisation_id"`
	UserID         int64              `json:"user_id"`
	Role           string             `json:"role"`
	District       *string            `json:"district"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PartnerApiKey struct {
	ID               int64              `json:"id"`
	OrganisationID   *int64             `json:"organisation_id"`
	Name             string             `json:"name"`
	Environment      string             `json:"environment"`
	KeyPrefix        string             `json:"key_prefix"`
	KeyHash          string             `json:"key_hash"`
	Scopes           []byte             `json:"scopes"`
	AllowedDistricts []byte             `json:"allowed_districts"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	LastUsedIp       *netip.Addr        `json:"last_used_ip"`
	CreatedByUserID  *int64             `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PartnerExportRun struct {
	ID                int64              `json:"id"`
	OrganisationID    *int64             `json:"organisation_id"`
	RequestedByUserID *int64             `json:"requested_by_user_id"`
	Format            string             `json:"format"`
	Scope             []byte             `json:"scope"`
	RecordCounts      []byte             `json:"record_counts"`
	Checksum          string             `json:"checksum"`
	Payload           []byte             `json:"payload"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PartnerWebhookEvent struct {
	ID             int64              `json:"id"`
	SubscriptionID int64              `json:"subscription_id"`
	EventType      string             `json:"event_type"`
	Payload        []byte             `json:"payload"`
	Metadata       []byte             `json:"metadata"`
	Status         string             `json:"status"`
	AttemptCount   int32              `json:"attempt_count"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
}

type PartnerWebhookSubscription struct {
	ID               int64              `json:"id"`
	OrganisationID   *int64             `json:"organisation_id"`
	Name             string             `json:"name"`
	TargetUrl        string             `json:"target_url"`
	EventTypes       []byte             `json:"event_types"`
	SecretHash       string             `json:"secret_hash"`
	Status           string             `json:"status"`
	LastTestedAt     pgtype.Timestamptz `json:"last_tested_at"`
	LastTestStatus   *string            `json:"last_test_status"`
	LastTestMetadata []byte             `json:"last_test_metadata"`
	LastError        *string            `json:"last_error"`
	CreatedByUserID  *int64             `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PilotIngestionRun struct {
	ID               string             `json:"id"`
	OrganisationID   int64              `json:"organisation_id"`
	SourceName       string             `json:"source_name"`
	SourceReference  string             `json:"source_reference"`
	Status           string             `json:"status"`
	RecordsReceived  int32              `json:"records_received"`
	RecordsImported  int32              `json:"records_imported"`
	RecordsRejected  int32              `json:"records_rejected"`
	ValidationErrors []byte             `json:"validation_errors"`
	ActorUserID      *int64             `json:"actor_user_id"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type Report struct {
	ID                int64              `json:"id"`
	ExternalID        *string            `json:"external_id"`
	ClinicID          string             `json:"clinic_id"`
	ReporterName      *string            `json:"reporter_name"`
	Source            string             `json:"source"`
	OfflineCreated    bool               `json:"offline_created"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	Status            string             `json:"status"`
	Reason            *string            `json:"reason"`
	StaffPressure     *string            `json:"staff_pressure"`
	StockPressure     *string            `json:"stock_pressure"`
	QueuePressure     *string            `json:"queue_pressure"`
	Notes             *string            `json:"notes"`
	ReviewState       string             `json:"review_state"`
	ConfidenceScore   pgtype.Numeric     `json:"confidence_score"`
	SubmittedByUserID *int64             `json:"submitted_by_user_id"`
	ReviewedByUserID  *int64             `json:"reviewed_by_user_id"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes       *string            `json:"review_notes"`
}

type ReportReview struct {
	ID             int64              `json:"id"`
	ReportID       int64              `json:"report_id"`
	ReviewerUserID int64              `json:"reviewer_user_id"`
	OrganisationID *int64             `json:"organisation_id"`
	Decision       string             `json:"decision"`
	Notes          *string            `json:"notes"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ReportSyncAttempt struct {
	ID                 int64              `json:"id"`
	ExternalID         string             `json:"external_id"`
	ReportID           *int64             `json:"report_id"`
	SubmittedByUserID  *int64             `json:"submitted_by_user_id"`
	OrganisationID     *int64             `json:"organisation_id"`
	ClinicID           *string            `json:"clinic_id"`
	Result             string             `json:"result"`
	ClientAttemptCount int32              `json:"client_attempt_count"`
	QueuedAt           pgtype.Timestamptz `json:"queued_at"`
	SubmittedAt        pgtype.Timestamptz `json:"submitted_at"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ErrorCode          *string            `json:"error_code"`
	ErrorMessage       *string            `json:"error_message"`
	Metadata           []byte             `json:"metadata"`
}

type Session struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	UserAgent  *string            `json:"user_agent"`
	IpAddress  *netip.Addr        `json:"ip_address"`
}

type User struct {
	ID                    int64              `json:"id"`
	Email                 string             `json:"email"`
	DisplayName           string             `json:"display_name"`
	PasswordHash          *string            `json:"password_hash"`
	DisabledAt            pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	PasswordChangedAt     pgtype.Timestamptz `json:"password_changed_at"`
	PasswordResetRequired bool               `json:"password_reset_required"`
}
