import type { Clinic } from "@/lib/demo/types";

export const DEMO_PROVINCE = "Gauteng";
export const DEMO_DISTRICT = "Tshwane North Demo District";

export const STOCKOUT_TRIGGER_CLINIC_ID = "clinic-mamelodi-east";
export const STAFFING_TRIGGER_CLINIC_ID = "clinic-soshanguve-block-f";

export const demoClinics: Clinic[] = [
  {
    id: "clinic-mamelodi-east",
    name: "Mamelodi East Community Clinic",
    facilityCode: "GP-TND-001",
    province: DEMO_PROVINCE,
    district: DEMO_DISTRICT,
    latitude: -25.7096,
    longitude: 28.3676,
    services: ["Primary care", "Maternal health", "HIV treatment", "Pharmacy"],
    operatingHours: "Mon-Sat 07:00-19:00",
    imageKey: "clinic-front-01",
  },
  {
    id: "clinic-soshanguve-block-f",
    name: "Soshanguve Block F Clinic",
    facilityCode: "GP-TND-002",
    province: DEMO_PROVINCE,
    district: DEMO_DISTRICT,
    latitude: -25.5393,
    longitude: 28.1012,
    services: ["Primary care", "TB screening", "Immunization", "Pharmacy"],
    operatingHours: "Mon-Fri 07:00-18:00",
    imageKey: "clinic-front-02",
  },
  {
    id: "clinic-ga-rankuwa-zone-1",
    name: "Ga-Rankuwa Zone 1 Clinic",
    facilityCode: "GP-TND-003",
    province: DEMO_PROVINCE,
    district: DEMO_DISTRICT,
    latitude: -25.6122,
    longitude: 27.9954,
    services: ["Primary care", "Lab collection", "HIV treatment"],
    operatingHours: "Mon-Sat 07:00-17:00",
    imageKey: "clinic-front-01",
  },
  {
    id: "clinic-hammanskraal-unit-d",
    name: "Hammanskraal Unit D Clinic",
    facilityCode: "GP-TND-004",
    province: DEMO_PROVINCE,
    district: DEMO_DISTRICT,
    latitude: -25.4047,
    longitude: 28.2794,
    services: ["Primary care", "Maternal health", "Emergency stabilization"],
    operatingHours: "24 hours",
    imageKey: "clinic-front-02",
  },
  {
    id: "clinic-mabopane-station",
    name: "Mabopane Station Clinic",
    facilityCode: "GP-TND-005",
    province: DEMO_PROVINCE,
    district: DEMO_DISTRICT,
    latitude: -25.4985,
    longitude: 28.0143,
    services: ["Primary care", "Pharmacy", "Immunization"],
    operatingHours: "Mon-Fri 08:00-16:00",
    imageKey: "clinic-front-01",
  },
  {
    id: "clinic-winterveldt-west",
    name: "Winterveldt West Clinic",
    facilityCode: "GP-TND-006",
    province: DEMO_PROVINCE,
    district: DEMO_DISTRICT,
    latitude: -25.4658,
    longitude: 27.9392,
    services: ["Primary care", "Chronic care", "Pharmacy"],
    operatingHours: "Mon-Fri 07:30-17:00",
    imageKey: "clinic-front-02",
  },
  {
    id: "clinic-atteridgeville-extension",
    name: "Atteridgeville Extension Clinic",
    facilityCode: "GP-TND-007",
    province: DEMO_PROVINCE,
    district: DEMO_DISTRICT,
    latitude: -25.7744,
    longitude: 27.9364,
    services: ["Primary care", "Maternal health", "Pharmacy", "Lab collection"],
    operatingHours: "Mon-Sat 07:00-18:00",
    imageKey: "clinic-front-01",
  },
  {
    id: "clinic-akasia-hills",
    name: "Akasia Hills Clinic",
    facilityCode: "GP-TND-008",
    province: DEMO_PROVINCE,
    district: DEMO_DISTRICT,
    latitude: -25.6694,
    longitude: 28.1027,
    services: ["Primary care", "Pharmacy", "Immunization", "HIV treatment"],
    operatingHours: "Mon-Fri 07:00-18:00",
    imageKey: "clinic-front-02",
  },
];
