import type { AuditEvent, ClinicCurrentState, ReportEvent } from "@/lib/demo/types";

export const demoClinicStates: ClinicCurrentState[] = [
  {
    clinicId: "clinic-mamelodi-east",
    status: "operational",
    reason: "All essential services available after morning stock reconciliation.",
    freshness: "fresh",
    lastReportedAt: "2026-05-01T06:40:00.000Z",
    reporterName: "Nomsa Dlamini",
    source: "clinic_coordinator",
    staffPressure: "normal",
    stockPressure: "low",
    queuePressure: "moderate",
  },
  {
    clinicId: "clinic-soshanguve-block-f",
    status: "operational",
    reason: "Facility open with one nurse absent but core service line still running.",
    freshness: "fresh",
    lastReportedAt: "2026-05-01T06:32:00.000Z",
    reporterName: "Peter Mokoena",
    source: "field_worker",
    staffPressure: "strained",
    stockPressure: "normal",
    queuePressure: "moderate",
  },
  {
    clinicId: "clinic-ga-rankuwa-zone-1",
    status: "degraded",
    reason: "Lab courier delay is slowing same-day results and repeat visits are stacking.",
    freshness: "fresh",
    lastReportedAt: "2026-05-01T05:58:00.000Z",
    reporterName: "Kagiso Tema",
    source: "field_worker",
    staffPressure: "strained",
    stockPressure: "normal",
    queuePressure: "high",
  },
  {
    clinicId: "clinic-hammanskraal-unit-d",
    status: "degraded",
    reason: "Antenatal services constrained after fridge maintenance paused vaccine storage.",
    freshness: "needs_confirmation",
    lastReportedAt: "2026-04-30T18:15:00.000Z",
    reporterName: "Lerato Maseko",
    source: "clinic_coordinator",
    staffPressure: "normal",
    stockPressure: "low",
    queuePressure: "moderate",
  },
  {
    clinicId: "clinic-mabopane-station",
    status: "non_functional",
    reason: "Power outage and generator fault forced the clinic to suspend dispensing.",
    freshness: "fresh",
    lastReportedAt: "2026-05-01T06:12:00.000Z",
    reporterName: "District Ops Desk",
    source: "seed",
    staffPressure: "critical",
    stockPressure: "unknown",
    queuePressure: "high",
  },
  {
    clinicId: "clinic-winterveldt-west",
    status: "unknown",
    reason: "No verified update since network blackout yesterday afternoon.",
    freshness: "stale",
    lastReportedAt: "2026-04-29T15:45:00.000Z",
    reporterName: "District Ops Desk",
    source: "seed",
    staffPressure: "unknown",
    stockPressure: "unknown",
    queuePressure: "unknown",
  },
  {
    clinicId: "clinic-atteridgeville-extension",
    status: "unknown",
    reason: "Conflicting field notes need confirmation from the clinic coordinator.",
    freshness: "stale",
    lastReportedAt: "2026-04-29T13:20:00.000Z",
    reporterName: "District Ops Desk",
    source: "seed",
    staffPressure: "unknown",
    stockPressure: "unknown",
    queuePressure: "unknown",
  },
  {
    clinicId: "clinic-akasia-hills",
    status: "operational",
    reason: "Facility open across all core services, with queue pressure elevated during the morning surge.",
    freshness: "fresh",
    lastReportedAt: "2026-05-01T06:05:00.000Z",
    reporterName: "Mpho Ndlovu",
    source: "clinic_coordinator",
    staffPressure: "strained",
    stockPressure: "normal",
    queuePressure: "high",
  },
];

export const demoReports: ReportEvent[] = [
  {
    id: "report-001",
    clinicId: "clinic-mamelodi-east",
    reporterName: "Nomsa Dlamini",
    source: "clinic_coordinator",
    offlineCreated: false,
    submittedAt: "2026-05-01T06:36:00.000Z",
    receivedAt: "2026-05-01T06:40:00.000Z",
    status: "operational",
    reason: "All essential services available after morning stock reconciliation.",
    staffPressure: "normal",
    stockPressure: "low",
    queuePressure: "moderate",
    notes: "Small queue at pharmacy but moving within target.",
  },
  {
    id: "report-002",
    clinicId: "clinic-soshanguve-block-f",
    reporterName: "Peter Mokoena",
    source: "field_worker",
    offlineCreated: false,
    submittedAt: "2026-05-01T06:28:00.000Z",
    receivedAt: "2026-05-01T06:32:00.000Z",
    status: "operational",
    reason: "Facility open with one nurse absent but core service line still running.",
    staffPressure: "strained",
    stockPressure: "normal",
    queuePressure: "moderate",
    notes: "Recommend monitoring afternoon staffing handoff.",
  },
  {
    id: "report-003",
    clinicId: "clinic-ga-rankuwa-zone-1",
    reporterName: "Kagiso Tema",
    source: "field_worker",
    offlineCreated: false,
    submittedAt: "2026-05-01T05:54:00.000Z",
    receivedAt: "2026-05-01T05:58:00.000Z",
    status: "degraded",
    reason: "Lab courier delay is slowing same-day results and repeat visits are stacking.",
    staffPressure: "strained",
    stockPressure: "normal",
    queuePressure: "high",
    notes: "Patients needing specimen confirmation are being asked to return after lunch.",
  },
  {
    id: "report-004",
    clinicId: "clinic-hammanskraal-unit-d",
    reporterName: "Lerato Maseko",
    source: "clinic_coordinator",
    offlineCreated: false,
    submittedAt: "2026-04-30T18:06:00.000Z",
    receivedAt: "2026-04-30T18:15:00.000Z",
    status: "degraded",
    reason: "Antenatal services constrained after fridge maintenance paused vaccine storage.",
    staffPressure: "normal",
    stockPressure: "low",
    queuePressure: "moderate",
    notes: "Cold chain contractor expected on site by 09:00.",
  },
  {
    id: "report-005",
    clinicId: "clinic-mabopane-station",
    reporterName: "District Ops Desk",
    source: "seed",
    offlineCreated: false,
    submittedAt: "2026-05-01T06:09:00.000Z",
    receivedAt: "2026-05-01T06:12:00.000Z",
    status: "non_functional",
    reason: "Power outage and generator fault forced the clinic to suspend dispensing.",
    staffPressure: "critical",
    stockPressure: "unknown",
    queuePressure: "high",
    notes: "Redirect chronic care pickups until generator vendor confirms ETA.",
  },
  {
    id: "report-006",
    clinicId: "clinic-winterveldt-west",
    reporterName: "District Ops Desk",
    source: "seed",
    offlineCreated: false,
    submittedAt: "2026-04-29T15:40:00.000Z",
    receivedAt: "2026-04-29T15:45:00.000Z",
    status: "unknown",
    reason: "No verified update since network blackout yesterday afternoon.",
    staffPressure: "unknown",
    stockPressure: "unknown",
    queuePressure: "unknown",
    notes: "Field follow-up still pending after signal loss.",
  },
  {
    id: "report-007",
    clinicId: "clinic-atteridgeville-extension",
    reporterName: "District Ops Desk",
    source: "seed",
    offlineCreated: false,
    submittedAt: "2026-04-29T13:15:00.000Z",
    receivedAt: "2026-04-29T13:20:00.000Z",
    status: "unknown",
    reason: "Conflicting field notes need confirmation from the clinic coordinator.",
    staffPressure: "unknown",
    stockPressure: "unknown",
    queuePressure: "unknown",
    notes: "One note reports medicine pickup only; another reports full closure.",
  },
  {
    id: "report-008",
    clinicId: "clinic-akasia-hills",
    reporterName: "Mpho Ndlovu",
    source: "clinic_coordinator",
    offlineCreated: false,
    submittedAt: "2026-05-01T06:01:00.000Z",
    receivedAt: "2026-05-01T06:05:00.000Z",
    status: "operational",
    reason: "Facility open across all core services, with queue pressure elevated during the morning surge.",
    staffPressure: "strained",
    stockPressure: "normal",
    queuePressure: "high",
    notes: "One overflow tent staffed; queues are elevated but service lines remain open.",
  },
  {
    id: "report-009",
    clinicId: "clinic-soshanguve-block-f",
    reporterName: "Peter Mokoena",
    source: "field_worker",
    offlineCreated: true,
    submittedAt: "2026-04-30T14:12:00.000Z",
    receivedAt: "2026-04-30T15:01:00.000Z",
    status: "operational",
    reason: "Connectivity restored after short outage; service resumed throughout the afternoon.",
    staffPressure: "normal",
    stockPressure: "normal",
    queuePressure: "low",
    notes: "Delayed upload from the previous round.",
  },
];

export const demoAuditEvents: AuditEvent[] = [
  {
    id: "audit-001",
    clinicId: "clinic-mabopane-station",
    actorName: "District Ops Desk",
    eventType: "alert.created",
    summary: "Critical downtime alert opened for power and generator failure.",
    createdAt: "2026-05-01T06:13:00.000Z",
  },
  {
    id: "audit-002",
    clinicId: "clinic-winterveldt-west",
    actorName: "District Ops Desk",
    eventType: "clinic.status_marked_stale",
    summary: "Clinic status marked stale after 36 hours without a verified report.",
    createdAt: "2026-04-30T04:00:00.000Z",
  },
  {
    id: "audit-003",
    clinicId: "clinic-atteridgeville-extension",
    actorName: "District Ops Desk",
    eventType: "clinic.status_marked_stale",
    summary: "Escalated conflicting status reports to the district manager queue.",
    createdAt: "2026-04-30T04:12:00.000Z",
  },
  {
    id: "audit-004",
    clinicId: "clinic-ga-rankuwa-zone-1",
    actorName: "Kagiso Tema",
    eventType: "report.submitted",
    summary: "Field worker submitted a degraded-status report citing courier delays.",
    createdAt: "2026-05-01T05:58:00.000Z",
  },
  {
    id: "audit-005",
    clinicId: "clinic-hammanskraal-unit-d",
    actorName: "Lerato Maseko",
    eventType: "report.submitted",
    summary: "Coordinator reported cold-chain disruption affecting antenatal services.",
    createdAt: "2026-04-30T18:15:00.000Z",
  },
  {
    id: "audit-006",
    clinicId: "clinic-mamelodi-east",
    actorName: "Nomsa Dlamini",
    eventType: "report.submitted",
    summary: "Morning readiness report confirmed all core services live.",
    createdAt: "2026-05-01T06:40:00.000Z",
  },
];
