// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (
    external_id,
    clinic_id,
    actor_name,
    event_type,
    summary,
    created_at,
    actor_user_id,
    actor_role,
    organisation_id,
    entity_type,
    entity_id,
    metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12::jsonb)
RETURNING
    id,
    external_id,
    clinic_id,
    actor_name,
    event_type,
    summary,
    created_at,
    actor_user_id,
    actor_role,
    organisation_id,
    entity_type,
    entity_id,
    metadata
`

type InsertAuditEventParams struct {
	ExternalID     *string            `json:"external_id"`
	ClinicID       *string            `json:"clinic_id"`
	ActorName      *string            `json:"actor_name"`
	EventType      string             `json:"event_type"`
	Summary        string             `json:"summary"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ActorUserID    *int64             `json:"actor_user_id"`
	ActorRole      *string            `json:"actor_role"`
	OrganisationID *int64             `json:"organisation_id"`
	EntityType     *string            `json:"entity_type"`
	EntityID       *string            `json:"entity_id"`
	Column12       []byte             `json:"column_12"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg *InsertAuditEventParams) (*AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ExternalID,
		arg.ClinicID,
		arg.ActorName,
		arg.EventType,
		arg.Summary,
		arg.CreatedAt,
		arg.ActorUserID,
		arg.ActorRole,
		arg.OrganisationID,
		arg.EntityType,
		arg.EntityID,
		arg.Column12,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ClinicID,
		&i.ActorName,
		&i.EventType,
		&i.Summary,
		&i.CreatedAt,
		&i.ActorUserID,
		&i.ActorRole,
		&i.OrganisationID,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
	)
	return &i, err
}

const listAdminAuditEvents = `-- name: ListAdminAuditEvents :many
SELECT
    id,
    external_id,
    clinic_id,
    actor_name,
    event_type,
    summary,
    created_at,
    actor_user_id,
    actor_role,
    organisation_id,
    entity_type,
    entity_id,
    metadata
FROM audit_events
WHERE $1 IS NULL OR organisation_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAdminAuditEventsParams struct {
	OrganisationID interface{} `json:"organisation_id"`
	Limit          int32       `json:"limit"`
}

func (q *Queries) ListAdminAuditEvents(ctx context.Context, arg *ListAdminAuditEventsParams) ([]*AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAdminAuditEvents, arg.OrganisationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.ClinicID,
			&i.ActorName,
			&i.EventType,
			&i.Summary,
			&i.CreatedAt,
			&i.ActorUserID,
			&i.ActorRole,
			&i.OrganisationID,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClinicAuditEvents = `-- name: ListClinicAuditEvents :many
SELECT
    id,
    external_id,
    clinic_id,
    actor_name,
    event_type,
    summary,
    created_at,
    actor_user_id,
    actor_role,
    organisation_id,
    entity_type,
    entity_id,
    metadata
FROM audit_events
WHERE clinic_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListClinicAuditEvents(ctx context.Context, clinicID *string) ([]*AuditEvent, error) {
	rows, err := q.db.Query(ctx, listClinicAuditEvents, clinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.ClinicID,
			&i.ActorName,
			&i.EventType,
			&i.Summary,
			&i.CreatedAt,
			&i.ActorUserID,
			&i.ActorRole,
			&i.OrganisationID,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
