// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id,
    token_hash,
    expires_at,
    user_agent,
    ip_address
)
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id,
    user_id,
    token_hash,
    created_at,
    expires_at,
    revoked_at,
    last_seen_at,
    user_agent,
    ip_address
`

type CreateSessionParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserAgent *string            `json:"user_agent"`
	IpAddress *string            `json:"ip_address"`
}

func (q *Queries) CreateSession(ctx context.Context, arg *CreateSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.UserAgent,
		&i.IpAddress,
	)
	return &i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash, password_reset_required, password_changed_at)
VALUES ($1, $2, $3, $4, CASE WHEN $3::text IS NULL THEN NULL ELSE now() END)
RETURNING id, email, display_name, password_hash, disabled_at, password_changed_at, password_reset_required, created_at, updated_at
`

type CreateUserParams struct {
	Email                 string  `json:"email"`
	DisplayName           string  `json:"display_name"`
	PasswordHash          *string `json:"password_hash"`
	PasswordResetRequired bool    `json:"password_reset_required"`
}

type CreateUserRow struct {
	ID                    int64              `json:"id"`
	Email                 string             `json:"email"`
	DisplayName           string             `json:"display_name"`
	PasswordHash          *string            `json:"password_hash"`
	DisabledAt            pgtype.Timestamptz `json:"disabled_at"`
	PasswordChangedAt     pgtype.Timestamptz `json:"password_changed_at"`
	PasswordResetRequired bool               `json:"password_reset_required"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.PasswordResetRequired,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.PasswordChangedAt,
		&i.PasswordResetRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteOrganisationMembershipsForUser = `-- name: DeleteOrganisationMembershipsForUser :exec
DELETE FROM organisation_memberships
WHERE user_id = $1
`

func (q *Queries) DeleteOrganisationMembershipsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteOrganisationMembershipsForUser, userID)
	return err
}

const disableUser = `-- name: DisableUser :execrows
UPDATE users SET disabled_at = $2, updated_at = now() WHERE id = $1 AND disabled_at IS NULL
`

type DisableUserParams struct {
	ID         int64              `json:"id"`
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
}

func (q *Queries) DisableUser(ctx context.Context, arg *DisableUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableUser, arg.ID, arg.DisabledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enableUser = `-- name: EnableUser :execrows
UPDATE users SET disabled_at = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) EnableUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, enableUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAdminUserAccessByUserID = `-- name: GetAdminUserAccessByUserID :one
SELECT user_id, email, display_name, disabled_at, created_at, role, organisation_id, district, last_seen_at
FROM admin_user_access
WHERE user_id = $1
ORDER BY
    CASE role
        WHEN 'system_admin' THEN 4
        WHEN 'org_admin' THEN 3
        WHEN 'district_manager' THEN 2
        WHEN 'reporter' THEN 1
        ELSE 0
    END DESC,
    organisation_id NULLS FIRST,
    district NULLS FIRST,
    membership_id
LIMIT 1
`

type GetAdminUserAccessByUserIDRow struct {
	UserID         int64              `json:"user_id"`
	Email          string             `json:"email"`
	DisplayName    string             `json:"display_name"`
	DisabledAt     pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Role           string             `json:"role"`
	OrganisationID *int64             `json:"organisation_id"`
	District       *string            `json:"district"`
	LastSeenAt     interface{}        `json:"last_seen_at"`
}

func (q *Queries) GetAdminUserAccessByUserID(ctx context.Context, userID int64) (*GetAdminUserAccessByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserAccessByUserID, userID)
	var i GetAdminUserAccessByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.Role,
		&i.OrganisationID,
		&i.District,
		&i.LastSeenAt,
	)
	return &i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
WITH active_session (
    session_id,
    session_user_id,
    session_token_hash,
    session_created_at,
    session_expires_at,
    session_revoked_at,
    session_last_seen_at,
    session_user_agent,
    session_ip_address,
    user_id,
    user_email,
    user_display_name,
    user_password_hash,
    user_disabled_at,
    user_password_changed_at,
    user_password_reset_required,
    user_created_at,
    user_updated_at
) AS (
    UPDATE sessions AS s
    SET last_seen_at = now()
    FROM users AS u
    WHERE s.user_id = u.id
        AND s.token_hash = $1
        AND s.revoked_at IS NULL
        AND s.expires_at > now()
        AND u.disabled_at IS NULL
    RETURNING
        s.id,
        s.user_id,
        s.token_hash,
        s.created_at,
        s.expires_at,
        s.revoked_at,
        s.last_seen_at,
        s.user_agent,
        s.ip_address,
        u.id,
        u.email,
        u.display_name,
        u.password_hash,
        u.disabled_at,
        u.password_changed_at,
        u.password_reset_required,
        u.created_at,
        u.updated_at
)
SELECT
    session_id,
    session_user_id,
    session_token_hash,
    session_created_at,
    session_expires_at,
    session_revoked_at,
    session_last_seen_at,
    session_user_agent,
    session_ip_address,
    user_id,
    user_email,
    user_display_name,
    user_password_hash,
    user_disabled_at,
    user_password_changed_at,
    user_password_reset_required,
    user_created_at,
    user_updated_at
FROM active_session
`

type GetSessionByTokenHashRow struct {
	SessionID                 int64              `json:"session_id"`
	SessionUserID             int64              `json:"session_user_id"`
	SessionTokenHash          string             `json:"session_token_hash"`
	SessionCreatedAt          pgtype.Timestamptz `json:"session_created_at"`
	SessionExpiresAt          pgtype.Timestamptz `json:"session_expires_at"`
	SessionRevokedAt          pgtype.Timestamptz `json:"session_revoked_at"`
	SessionLastSeenAt         pgtype.Timestamptz `json:"session_last_seen_at"`
	SessionUserAgent          *string            `json:"session_user_agent"`
	SessionIpAddress          *string            `json:"session_ip_address"`
	UserID                    int64              `json:"user_id"`
	UserEmail                 string             `json:"user_email"`
	UserDisplayName           string             `json:"user_display_name"`
	UserPasswordHash          *string            `json:"user_password_hash"`
	UserDisabledAt            pgtype.Timestamptz `json:"user_disabled_at"`
	UserPasswordChangedAt     pgtype.Timestamptz `json:"user_password_changed_at"`
	UserPasswordResetRequired bool               `json:"user_password_reset_required"`
	UserCreatedAt             pgtype.Timestamptz `json:"user_created_at"`
	UserUpdatedAt             pgtype.Timestamptz `json:"user_updated_at"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (*GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionUserID,
		&i.SessionTokenHash,
		&i.SessionCreatedAt,
		&i.SessionExpiresAt,
		&i.SessionRevokedAt,
		&i.SessionLastSeenAt,
		&i.SessionUserAgent,
		&i.SessionIpAddress,
		&i.UserID,
		&i.UserEmail,
		&i.UserDisplayName,
		&i.UserPasswordHash,
		&i.UserDisabledAt,
		&i.UserPasswordChangedAt,
		&i.UserPasswordResetRequired,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    email,
    display_name,
    password_hash,
    disabled_at,
    password_changed_at,
    password_reset_required,
    created_at,
    updated_at
FROM users
WHERE lower(email) = lower($1)
`

type GetUserByEmailRow struct {
	ID                    int64              `json:"id"`
	Email                 string             `json:"email"`
	DisplayName           string             `json:"display_name"`
	PasswordHash          *string            `json:"password_hash"`
	DisabledAt            pgtype.Timestamptz `json:"disabled_at"`
	PasswordChangedAt     pgtype.Timestamptz `json:"password_changed_at"`
	PasswordResetRequired bool               `json:"password_reset_required"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (*GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.PasswordChangedAt,
		&i.PasswordResetRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, password_hash, disabled_at, password_changed_at, password_reset_required, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID                    int64              `json:"id"`
	Email                 string             `json:"email"`
	DisplayName           string             `json:"display_name"`
	PasswordHash          *string            `json:"password_hash"`
	DisabledAt            pgtype.Timestamptz `json:"disabled_at"`
	PasswordChangedAt     pgtype.Timestamptz `json:"password_changed_at"`
	PasswordResetRequired bool               `json:"password_reset_required"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (*GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.PasswordChangedAt,
		&i.PasswordResetRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertOrganisationMembership = `-- name: InsertOrganisationMembership :one
INSERT INTO organisation_memberships (user_id, organisation_id, role, district)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, organisation_id, role, district, created_at
`

type InsertOrganisationMembershipParams struct {
	UserID         int64   `json:"user_id"`
	OrganisationID *int64  `json:"organisation_id"`
	Role           string  `json:"role"`
	District       *string `json:"district"`
}

type InsertOrganisationMembershipRow struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	OrganisationID *int64             `json:"organisation_id"`
	Role           string             `json:"role"`
	District       *string            `json:"district"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertOrganisationMembership(ctx context.Context, arg *InsertOrganisationMembershipParams) (*InsertOrganisationMembershipRow, error) {
	row := q.db.QueryRow(ctx, insertOrganisationMembership,
		arg.UserID,
		arg.OrganisationID,
		arg.Role,
		arg.District,
	)
	var i InsertOrganisationMembershipRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganisationID,
		&i.Role,
		&i.District,
		&i.CreatedAt,
	)
	return &i, err
}

const listAdminUserAccess = `-- name: ListAdminUserAccess :many
SELECT
    users.id,
    users.email,
    users.display_name,
    users.disabled_at,
    users.created_at,
    organisation_memberships.role,
    organisation_memberships.organisation_id,
    organisation_memberships.district,
    max(sessions.last_seen_at) AS last_seen_at
FROM users
JOIN organisation_memberships ON organisation_memberships.user_id = users.id
LEFT JOIN sessions ON sessions.user_id = users.id AND sessions.revoked_at IS NULL AND sessions.expires_at > now()
WHERE $1 IS NULL OR organisation_memberships.organisation_id = $1
GROUP BY users.id, organisation_memberships.id
ORDER BY organisation_memberships.role, users.display_name, users.id
`

type ListAdminUserAccessRow struct {
	ID             int64              `json:"id"`
	Email          string             `json:"email"`
	DisplayName    string             `json:"display_name"`
	DisabledAt     pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Role           string             `json:"role"`
	OrganisationID *int64             `json:"organisation_id"`
	District       *string            `json:"district"`
	LastSeenAt     interface{}        `json:"last_seen_at"`
}

func (q *Queries) ListAdminUserAccess(ctx context.Context, dollar_1 interface{}) ([]*ListAdminUserAccessRow, error) {
	rows, err := q.db.Query(ctx, listAdminUserAccess, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAdminUserAccessRow
	for rows.Next() {
		var i ListAdminUserAccessRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.Role,
			&i.OrganisationID,
			&i.District,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT
    id,
    user_id,
    organisation_id,
    role,
    district,
    created_at
FROM organisation_memberships
WHERE user_id = $1
ORDER BY role, organisation_id NULLS FIRST, district NULLS FIRST, id
`

type ListMembershipsForUserRow struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	OrganisationID *int64             `json:"organisation_id"`
	Role           string             `json:"role"`
	District       *string            `json:"district"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMembershipsForUser(ctx context.Context, userID int64) ([]*ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListMembershipsForUserRow
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganisationID,
			&i.Role,
			&i.District,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForMembershipReplacement = `-- name: LockUserForMembershipReplacement :one
SELECT id
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockUserForMembershipReplacement(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUserForMembershipReplacement, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const revokeActiveSessionsForUser = `-- name: RevokeActiveSessionsForUser :execrows
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) RevokeActiveSessionsForUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActiveSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1
    AND revoked_at IS NULL
    AND expires_at > now()
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const updateUserLifecycle = `-- name: UpdateUserLifecycle :one
UPDATE users
SET
    display_name = COALESCE($2, display_name),
    disabled_at = CASE WHEN $3::boolean THEN COALESCE(disabled_at, $4) ELSE NULL END,
    updated_at = $4
WHERE id = $1
RETURNING id, email, display_name, password_hash, disabled_at, password_changed_at, password_reset_required, created_at, updated_at
`

type UpdateUserLifecycleParams struct {
	ID          int64              `json:"id"`
	DisplayName string             `json:"display_name"`
	Column3     bool               `json:"column_3"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UpdateUserLifecycleRow struct {
	ID                    int64              `json:"id"`
	Email                 string             `json:"email"`
	DisplayName           string             `json:"display_name"`
	PasswordHash          *string            `json:"password_hash"`
	DisabledAt            pgtype.Timestamptz `json:"disabled_at"`
	PasswordChangedAt     pgtype.Timestamptz `json:"password_changed_at"`
	PasswordResetRequired bool               `json:"password_reset_required"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserLifecycle(ctx context.Context, arg *UpdateUserLifecycleParams) (*UpdateUserLifecycleRow, error) {
	row := q.db.QueryRow(ctx, updateUserLifecycle,
		arg.ID,
		arg.DisplayName,
		arg.Column3,
		arg.UpdatedAt,
	)
	var i UpdateUserLifecycleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.PasswordChangedAt,
		&i.PasswordResetRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserLifecycleName = `-- name: UpdateUserLifecycleName :one
UPDATE users
SET
    display_name = COALESCE($2, display_name),
    updated_at = $3
WHERE id = $1
RETURNING id, email, display_name, password_hash, disabled_at, password_changed_at, password_reset_required, created_at, updated_at
`

type UpdateUserLifecycleNameParams struct {
	ID          int64              `json:"id"`
	DisplayName string             `json:"display_name"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UpdateUserLifecycleNameRow struct {
	ID                    int64              `json:"id"`
	Email                 string             `json:"email"`
	DisplayName           string             `json:"display_name"`
	PasswordHash          *string            `json:"password_hash"`
	DisabledAt            pgtype.Timestamptz `json:"disabled_at"`
	PasswordChangedAt     pgtype.Timestamptz `json:"password_changed_at"`
	PasswordResetRequired bool               `json:"password_reset_required"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserLifecycleName(ctx context.Context, arg *UpdateUserLifecycleNameParams) (*UpdateUserLifecycleNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserLifecycleName, arg.ID, arg.DisplayName, arg.UpdatedAt)
	var i UpdateUserLifecycleNameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.PasswordChangedAt,
		&i.PasswordResetRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2,
    password_changed_at = now(),
    password_reset_required = false,
    updated_at = now()
WHERE id = $1
RETURNING id, email, display_name, password_hash, disabled_at, password_changed_at, password_reset_required, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID           int64   `json:"id"`
	PasswordHash *string `json:"password_hash"`
}

type UpdateUserPasswordRow struct {
	ID                    int64              `json:"id"`
	Email                 string             `json:"email"`
	DisplayName           string             `json:"display_name"`
	PasswordHash          *string            `json:"password_hash"`
	DisabledAt            pgtype.Timestamptz `json:"disabled_at"`
	PasswordChangedAt     pgtype.Timestamptz `json:"password_changed_at"`
	PasswordResetRequired bool               `json:"password_reset_required"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) (*UpdateUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i UpdateUserPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.PasswordChangedAt,
		&i.PasswordResetRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
