// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clinics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClinic = `-- name: GetClinic :one
SELECT
    id,
    name,
    facility_code,
    province,
    district,
    latitude::double precision,
    longitude::double precision,
    operating_hours,
    facility_type,
    verification_status,
    last_verified_at,
    created_at,
    updated_at
FROM clinics
WHERE id = $1
`

type GetClinicRow struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	FacilityCode       string             `json:"facility_code"`
	Province           string             `json:"province"`
	District           string             `json:"district"`
	Latitude           float64            `json:"latitude"`
	Longitude          float64            `json:"longitude"`
	OperatingHours     *string            `json:"operating_hours"`
	FacilityType       string             `json:"facility_type"`
	VerificationStatus string             `json:"verification_status"`
	LastVerifiedAt     pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetClinic(ctx context.Context, id string) (*GetClinicRow, error) {
	row := q.db.QueryRow(ctx, getClinic, id)
	var i GetClinicRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FacilityCode,
		&i.Province,
		&i.District,
		&i.Latitude,
		&i.Longitude,
		&i.OperatingHours,
		&i.FacilityType,
		&i.VerificationStatus,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getClinicDistrict = `-- name: GetClinicDistrict :one
SELECT district FROM clinics WHERE id = $1
`

func (q *Queries) GetClinicDistrict(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getClinicDistrict, id)
	var district string
	err := row.Scan(&district)
	return district, err
}

const getCurrentStatus = `-- name: GetCurrentStatus :one
SELECT
    clinic_id,
    status,
    reason,
    freshness,
    last_reported_at,
    reporter_name,
    source,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    confidence_score::double precision,
    updated_at
FROM current_status
WHERE clinic_id = $1
`

type GetCurrentStatusRow struct {
	ClinicID        string             `json:"clinic_id"`
	Status          string             `json:"status"`
	Reason          *string            `json:"reason"`
	Freshness       string             `json:"freshness"`
	LastReportedAt  pgtype.Timestamptz `json:"last_reported_at"`
	ReporterName    *string            `json:"reporter_name"`
	Source          *string            `json:"source"`
	StaffPressure   *string            `json:"staff_pressure"`
	StockPressure   *string            `json:"stock_pressure"`
	QueuePressure   *string            `json:"queue_pressure"`
	ConfidenceScore float64            `json:"confidence_score"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCurrentStatus(ctx context.Context, clinicID string) (*GetCurrentStatusRow, error) {
	row := q.db.QueryRow(ctx, getCurrentStatus, clinicID)
	var i GetCurrentStatusRow
	err := row.Scan(
		&i.ClinicID,
		&i.Status,
		&i.Reason,
		&i.Freshness,
		&i.LastReportedAt,
		&i.ReporterName,
		&i.Source,
		&i.StaffPressure,
		&i.StockPressure,
		&i.QueuePressure,
		&i.ConfidenceScore,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCurrentStatusForUpdate = `-- name: GetCurrentStatusForUpdate :one
SELECT
    clinic_id,
    status,
    reason,
    freshness,
    last_reported_at,
    reporter_name,
    source,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    confidence_score::double precision,
    updated_at
FROM current_status
WHERE clinic_id = $1
FOR UPDATE
`

type GetCurrentStatusForUpdateRow struct {
	ClinicID        string             `json:"clinic_id"`
	Status          string             `json:"status"`
	Reason          *string            `json:"reason"`
	Freshness       string             `json:"freshness"`
	LastReportedAt  pgtype.Timestamptz `json:"last_reported_at"`
	ReporterName    *string            `json:"reporter_name"`
	Source          *string            `json:"source"`
	StaffPressure   *string            `json:"staff_pressure"`
	StockPressure   *string            `json:"stock_pressure"`
	QueuePressure   *string            `json:"queue_pressure"`
	ConfidenceScore float64            `json:"confidence_score"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCurrentStatusForUpdate(ctx context.Context, clinicID string) (*GetCurrentStatusForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCurrentStatusForUpdate, clinicID)
	var i GetCurrentStatusForUpdateRow
	err := row.Scan(
		&i.ClinicID,
		&i.Status,
		&i.Reason,
		&i.Freshness,
		&i.LastReportedAt,
		&i.ReporterName,
		&i.Source,
		&i.StaffPressure,
		&i.StockPressure,
		&i.QueuePressure,
		&i.ConfidenceScore,
		&i.UpdatedAt,
	)
	return &i, err
}

const listClinicServices = `-- name: ListClinicServices :many
SELECT
    clinic_id,
    service_name,
    current_availability,
    confidence_score::double precision,
    last_verified_at
FROM clinic_services
WHERE clinic_id = $1
ORDER BY service_name
`

type ListClinicServicesRow struct {
	ClinicID            string             `json:"clinic_id"`
	ServiceName         string             `json:"service_name"`
	CurrentAvailability string             `json:"current_availability"`
	ConfidenceScore     float64            `json:"confidence_score"`
	LastVerifiedAt      pgtype.Timestamptz `json:"last_verified_at"`
}

func (q *Queries) ListClinicServices(ctx context.Context, clinicID string) ([]*ListClinicServicesRow, error) {
	rows, err := q.db.Query(ctx, listClinicServices, clinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListClinicServicesRow
	for rows.Next() {
		var i ListClinicServicesRow
		if err := rows.Scan(
			&i.ClinicID,
			&i.ServiceName,
			&i.CurrentAvailability,
			&i.ConfidenceScore,
			&i.LastVerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClinics = `-- name: ListClinics :many

SELECT
    id,
    name,
    facility_code,
    province,
    district,
    latitude::double precision,
    longitude::double precision,
    operating_hours,
    facility_type,
    verification_status,
    last_verified_at,
    created_at,
    updated_at
FROM clinics
ORDER BY name
`

type ListClinicsRow struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	FacilityCode       string             `json:"facility_code"`
	Province           string             `json:"province"`
	District           string             `json:"district"`
	Latitude           float64            `json:"latitude"`
	Longitude          float64            `json:"longitude"`
	OperatingHours     *string            `json:"operating_hours"`
	FacilityType       string             `json:"facility_type"`
	VerificationStatus string             `json:"verification_status"`
	LastVerifiedAt     pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// clinics
func (q *Queries) ListClinics(ctx context.Context) ([]*ListClinicsRow, error) {
	rows, err := q.db.Query(ctx, listClinics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListClinicsRow
	for rows.Next() {
		var i ListClinicsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FacilityCode,
			&i.Province,
			&i.District,
			&i.Latitude,
			&i.Longitude,
			&i.OperatingHours,
			&i.FacilityType,
			&i.VerificationStatus,
			&i.LastVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentStatuses = `-- name: ListCurrentStatuses :many
SELECT
    clinic_id,
    status,
    reason,
    freshness,
    last_reported_at,
    reporter_name,
    source,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    confidence_score::double precision,
    updated_at
FROM current_status
ORDER BY clinic_id
`

type ListCurrentStatusesRow struct {
	ClinicID        string             `json:"clinic_id"`
	Status          string             `json:"status"`
	Reason          *string            `json:"reason"`
	Freshness       string             `json:"freshness"`
	LastReportedAt  pgtype.Timestamptz `json:"last_reported_at"`
	ReporterName    *string            `json:"reporter_name"`
	Source          *string            `json:"source"`
	StaffPressure   *string            `json:"staff_pressure"`
	StockPressure   *string            `json:"stock_pressure"`
	QueuePressure   *string            `json:"queue_pressure"`
	ConfidenceScore float64            `json:"confidence_score"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCurrentStatuses(ctx context.Context) ([]*ListCurrentStatusesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCurrentStatusesRow
	for rows.Next() {
		var i ListCurrentStatusesRow
		if err := rows.Scan(
			&i.ClinicID,
			&i.Status,
			&i.Reason,
			&i.Freshness,
			&i.LastReportedAt,
			&i.ReporterName,
			&i.Source,
			&i.StaffPressure,
			&i.StockPressure,
			&i.QueuePressure,
			&i.ConfidenceScore,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentStatusesForReviewScope = `-- name: ListCurrentStatusesForReviewScope :many
SELECT
    current_status.clinic_id,
    current_status.status,
    current_status.reason,
    current_status.freshness,
    current_status.last_reported_at,
    current_status.reporter_name,
    current_status.source,
    current_status.staff_pressure,
    current_status.stock_pressure,
    current_status.queue_pressure,
    current_status.confidence_score::double precision,
    current_status.updated_at
FROM current_status
JOIN clinics ON clinics.id = current_status.clinic_id
WHERE (
    ($1 = 'district_manager' AND $2::text IS NOT NULL AND clinics.district = $2)
    OR $1 IN ('org_admin', 'system_admin')
)
ORDER BY current_status.clinic_id
`

type ListCurrentStatusesForReviewScopeParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 string      `json:"column_2"`
}

type ListCurrentStatusesForReviewScopeRow struct {
	ClinicID                     string             `json:"clinic_id"`
	Status                       string             `json:"status"`
	Reason                       *string            `json:"reason"`
	Freshness                    string             `json:"freshness"`
	LastReportedAt               pgtype.Timestamptz `json:"last_reported_at"`
	ReporterName                 *string            `json:"reporter_name"`
	Source                       *string            `json:"source"`
	StaffPressure                *string            `json:"staff_pressure"`
	StockPressure                *string            `json:"stock_pressure"`
	QueuePressure                *string            `json:"queue_pressure"`
	CurrentStatusConfidenceScore float64            `json:"current_status_confidence_score"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCurrentStatusesForReviewScope(ctx context.Context, arg *ListCurrentStatusesForReviewScopeParams) ([]*ListCurrentStatusesForReviewScopeRow, error) {
	rows, err := q.db.Query(ctx, listCurrentStatusesForReviewScope, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCurrentStatusesForReviewScopeRow
	for rows.Next() {
		var i ListCurrentStatusesForReviewScopeRow
		if err := rows.Scan(
			&i.ClinicID,
			&i.Status,
			&i.Reason,
			&i.Freshness,
			&i.LastReportedAt,
			&i.ReporterName,
			&i.Source,
			&i.StaffPressure,
			&i.StockPressure,
			&i.QueuePressure,
			&i.CurrentStatusConfidenceScore,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurrentStatusFreshness = `-- name: UpdateCurrentStatusFreshness :one
UPDATE current_status
SET
    freshness = $2,
    updated_at = $3
WHERE clinic_id = $1
    AND freshness <> $2
RETURNING
    clinic_id,
    status,
    reason,
    freshness,
    last_reported_at,
    reporter_name,
    source,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    confidence_score::double precision,
    updated_at
`

type UpdateCurrentStatusFreshnessParams struct {
	ClinicID  string             `json:"clinic_id"`
	Freshness string             `json:"freshness"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UpdateCurrentStatusFreshnessRow struct {
	ClinicID        string             `json:"clinic_id"`
	Status          string             `json:"status"`
	Reason          *string            `json:"reason"`
	Freshness       string             `json:"freshness"`
	LastReportedAt  pgtype.Timestamptz `json:"last_reported_at"`
	ReporterName    *string            `json:"reporter_name"`
	Source          *string            `json:"source"`
	StaffPressure   *string            `json:"staff_pressure"`
	StockPressure   *string            `json:"stock_pressure"`
	QueuePressure   *string            `json:"queue_pressure"`
	ConfidenceScore float64            `json:"confidence_score"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCurrentStatusFreshness(ctx context.Context, arg *UpdateCurrentStatusFreshnessParams) (*UpdateCurrentStatusFreshnessRow, error) {
	row := q.db.QueryRow(ctx, updateCurrentStatusFreshness, arg.ClinicID, arg.Freshness, arg.UpdatedAt)
	var i UpdateCurrentStatusFreshnessRow
	err := row.Scan(
		&i.ClinicID,
		&i.Status,
		&i.Reason,
		&i.Freshness,
		&i.LastReportedAt,
		&i.ReporterName,
		&i.Source,
		&i.StaffPressure,
		&i.StockPressure,
		&i.QueuePressure,
		&i.ConfidenceScore,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertCurrentStatus = `-- name: UpsertCurrentStatus :one
INSERT INTO current_status (
    clinic_id,
    status,
    reason,
    freshness,
    last_reported_at,
    reporter_name,
    source,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    confidence_score,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (clinic_id) DO UPDATE SET
    status = EXCLUDED.status,
    reason = EXCLUDED.reason,
    freshness = EXCLUDED.freshness,
    last_reported_at = EXCLUDED.last_reported_at,
    reporter_name = EXCLUDED.reporter_name,
    source = EXCLUDED.source,
    staff_pressure = EXCLUDED.staff_pressure,
    stock_pressure = EXCLUDED.stock_pressure,
    queue_pressure = EXCLUDED.queue_pressure,
    confidence_score = EXCLUDED.confidence_score,
    updated_at = EXCLUDED.updated_at
WHERE current_status.last_reported_at IS NULL
    OR EXCLUDED.last_reported_at >= current_status.last_reported_at
RETURNING
    clinic_id,
    status,
    reason,
    freshness,
    last_reported_at,
    reporter_name,
    source,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    confidence_score::double precision,
    updated_at
`

type UpsertCurrentStatusParams struct {
	ClinicID        string             `json:"clinic_id"`
	Status          string             `json:"status"`
	Reason          *string            `json:"reason"`
	Freshness       string             `json:"freshness"`
	LastReportedAt  pgtype.Timestamptz `json:"last_reported_at"`
	ReporterName    *string            `json:"reporter_name"`
	Source          *string            `json:"source"`
	StaffPressure   *string            `json:"staff_pressure"`
	StockPressure   *string            `json:"stock_pressure"`
	QueuePressure   *string            `json:"queue_pressure"`
	ConfidenceScore pgtype.Numeric     `json:"confidence_score"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UpsertCurrentStatusRow struct {
	ClinicID        string             `json:"clinic_id"`
	Status          string             `json:"status"`
	Reason          *string            `json:"reason"`
	Freshness       string             `json:"freshness"`
	LastReportedAt  pgtype.Timestamptz `json:"last_reported_at"`
	ReporterName    *string            `json:"reporter_name"`
	Source          *string            `json:"source"`
	StaffPressure   *string            `json:"staff_pressure"`
	StockPressure   *string            `json:"stock_pressure"`
	QueuePressure   *string            `json:"queue_pressure"`
	ConfidenceScore float64            `json:"confidence_score"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertCurrentStatus(ctx context.Context, arg *UpsertCurrentStatusParams) (*UpsertCurrentStatusRow, error) {
	row := q.db.QueryRow(ctx, upsertCurrentStatus,
		arg.ClinicID,
		arg.Status,
		arg.Reason,
		arg.Freshness,
		arg.LastReportedAt,
		arg.ReporterName,
		arg.Source,
		arg.StaffPressure,
		arg.StockPressure,
		arg.QueuePressure,
		arg.ConfidenceScore,
		arg.UpdatedAt,
	)
	var i UpsertCurrentStatusRow
	err := row.Scan(
		&i.ClinicID,
		&i.Status,
		&i.Reason,
		&i.Freshness,
		&i.LastReportedAt,
		&i.ReporterName,
		&i.Source,
		&i.StaffPressure,
		&i.StockPressure,
		&i.QueuePressure,
		&i.ConfidenceScore,
		&i.UpdatedAt,
	)
	return &i, err
}

const verifyClinicExists = `-- name: VerifyClinicExists :one
SELECT id FROM clinics WHERE id = $1
`

func (q *Queries) VerifyClinicExists(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, verifyClinicExists, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}
