// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingestion.sql

package db

import (
	"context"
)

const listPilotIngestionRuns = `-- name: ListPilotIngestionRuns :many
SELECT
    id,
    organisation_id,
    source_name,
    source_reference,
    status,
    records_received,
    records_imported,
    records_rejected,
    validation_errors,
    actor_user_id,
    started_at,
    completed_at
FROM pilot_ingestion_runs
WHERE $1::bigint IS NULL OR organisation_id = $1
ORDER BY started_at DESC, id DESC
LIMIT $2
`

type ListPilotIngestionRunsParams struct {
	OrganisationID *int64 `json:"organisation_id"`
	Limit          int32  `json:"limit"`
}

func (q *Queries) ListPilotIngestionRuns(ctx context.Context, arg *ListPilotIngestionRunsParams) ([]*PilotIngestionRun, error) {
	rows, err := q.db.Query(ctx, listPilotIngestionRuns, arg.OrganisationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PilotIngestionRun
	for rows.Next() {
		var i PilotIngestionRun
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.SourceName,
			&i.SourceReference,
			&i.Status,
			&i.RecordsReceived,
			&i.RecordsImported,
			&i.RecordsRejected,
			&i.ValidationErrors,
			&i.ActorUserID,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
