// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partner.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestPartnerExportRun = `-- name: GetLatestPartnerExportRun :one
SELECT
    id,
    organisation_id,
    requested_by_user_id,
    format,
    scope,
    record_counts,
    checksum,
    payload,
    created_at
FROM partner_export_runs
WHERE $1 IS NULL OR organisation_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestPartnerExportRun(ctx context.Context, organisationID interface{}) (*PartnerExportRun, error) {
	row := q.db.QueryRow(ctx, getLatestPartnerExportRun, organisationID)
	var i PartnerExportRun
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.RequestedByUserID,
		&i.Format,
		&i.Scope,
		&i.RecordCounts,
		&i.Checksum,
		&i.Payload,
		&i.CreatedAt,
	)
	return &i, err
}

const getPartnerAPIKeyByHash = `-- name: GetPartnerAPIKeyByHash :one
SELECT
    id,
    organisation_id,
    name,
    environment,
    key_prefix,
    key_hash,
    scopes,
    allowed_districts,
    expires_at,
    revoked_at,
    last_used_at,
    host(last_used_ip) AS last_used_ip,
    created_by_user_id,
    created_at,
    updated_at
FROM partner_api_keys
WHERE key_hash = $1
`

type GetPartnerAPIKeyByHashRow struct {
	ID               int64              `json:"id"`
	OrganisationID   *int64             `json:"organisation_id"`
	Name             string             `json:"name"`
	Environment      string             `json:"environment"`
	KeyPrefix        string             `json:"key_prefix"`
	KeyHash          string             `json:"key_hash"`
	Scopes           []byte             `json:"scopes"`
	AllowedDistricts []byte             `json:"allowed_districts"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	LastUsedIp       string             `json:"last_used_ip"`
	CreatedByUserID  *int64             `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPartnerAPIKeyByHash(ctx context.Context, keyHash string) (*GetPartnerAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getPartnerAPIKeyByHash, keyHash)
	var i GetPartnerAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Environment,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.AllowedDistricts,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPartnerAPIKeyState = `-- name: GetPartnerAPIKeyState :one
SELECT
    revoked_at,
    expires_at
FROM partner_api_keys
WHERE id = $1
`

type GetPartnerAPIKeyStateRow struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetPartnerAPIKeyState(ctx context.Context, id int64) (*GetPartnerAPIKeyStateRow, error) {
	row := q.db.QueryRow(ctx, getPartnerAPIKeyState, id)
	var i GetPartnerAPIKeyStateRow
	err := row.Scan(&i.RevokedAt, &i.ExpiresAt)
	return &i, err
}

const getPartnerExportRun = `-- name: GetPartnerExportRun :one
SELECT
    id,
    organisation_id,
    requested_by_user_id,
    format,
    scope,
    record_counts,
    checksum,
    payload,
    created_at
FROM partner_export_runs
WHERE id = $1
`

func (q *Queries) GetPartnerExportRun(ctx context.Context, id int64) (*PartnerExportRun, error) {
	row := q.db.QueryRow(ctx, getPartnerExportRun, id)
	var i PartnerExportRun
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.RequestedByUserID,
		&i.Format,
		&i.Scope,
		&i.RecordCounts,
		&i.Checksum,
		&i.Payload,
		&i.CreatedAt,
	)
	return &i, err
}

const getPartnerExportRunForOrganisation = `-- name: GetPartnerExportRunForOrganisation :one
SELECT
    id,
    organisation_id,
    requested_by_user_id,
    format,
    scope,
    record_counts,
    checksum,
    payload,
    created_at
FROM partner_export_runs
WHERE id = $1
    AND ($2 IS NULL OR organisation_id = $2)
`

type GetPartnerExportRunForOrganisationParams struct {
	ID             int64       `json:"id"`
	OrganisationID interface{} `json:"organisation_id"`
}

func (q *Queries) GetPartnerExportRunForOrganisation(ctx context.Context, arg *GetPartnerExportRunForOrganisationParams) (*PartnerExportRun, error) {
	row := q.db.QueryRow(ctx, getPartnerExportRunForOrganisation, arg.ID, arg.OrganisationID)
	var i PartnerExportRun
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.RequestedByUserID,
		&i.Format,
		&i.Scope,
		&i.RecordCounts,
		&i.Checksum,
		&i.Payload,
		&i.CreatedAt,
	)
	return &i, err
}

const insertPartnerAPIKey = `-- name: InsertPartnerAPIKey :one
INSERT INTO partner_api_keys (
    organisation_id,
    name,
    environment,
    key_prefix,
    key_hash,
    scopes,
    allowed_districts,
    expires_at,
    created_by_user_id,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, $8, $9, $10, $10)
RETURNING
    id,
    organisation_id,
    name,
    environment,
    key_prefix,
    key_hash,
    scopes,
    allowed_districts,
    expires_at,
    revoked_at,
    last_used_at,
    host(last_used_ip) AS last_used_ip,
    created_by_user_id,
    created_at,
    updated_at
`

type InsertPartnerAPIKeyParams struct {
	OrganisationID  *int64             `json:"organisation_id"`
	Name            string             `json:"name"`
	Environment     string             `json:"environment"`
	KeyPrefix       string             `json:"key_prefix"`
	KeyHash         string             `json:"key_hash"`
	Column6         []byte             `json:"column_6"`
	Column7         []byte             `json:"column_7"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedByUserID *int64             `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type InsertPartnerAPIKeyRow struct {
	ID               int64              `json:"id"`
	OrganisationID   *int64             `json:"organisation_id"`
	Name             string             `json:"name"`
	Environment      string             `json:"environment"`
	KeyPrefix        string             `json:"key_prefix"`
	KeyHash          string             `json:"key_hash"`
	Scopes           []byte             `json:"scopes"`
	AllowedDistricts []byte             `json:"allowed_districts"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	LastUsedIp       string             `json:"last_used_ip"`
	CreatedByUserID  *int64             `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertPartnerAPIKey(ctx context.Context, arg *InsertPartnerAPIKeyParams) (*InsertPartnerAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, insertPartnerAPIKey,
		arg.OrganisationID,
		arg.Name,
		arg.Environment,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Column6,
		arg.Column7,
		arg.ExpiresAt,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i InsertPartnerAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.Environment,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.AllowedDistricts,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertPartnerExportRun = `-- name: InsertPartnerExportRun :one
INSERT INTO partner_export_runs (
    organisation_id,
    requested_by_user_id,
    format,
    scope,
    record_counts,
    checksum,
    payload,
    created_at
)
VALUES ($1, $2, $3, $4::jsonb, $5::jsonb, $6, $7::jsonb, $8)
RETURNING
    id,
    organisation_id,
    requested_by_user_id,
    format,
    scope,
    record_counts,
    checksum,
    payload,
    created_at
`

type InsertPartnerExportRunParams struct {
	OrganisationID    *int64             `json:"organisation_id"`
	RequestedByUserID *int64             `json:"requested_by_user_id"`
	Format            string             `json:"format"`
	Column4           []byte             `json:"column_4"`
	Column5           []byte             `json:"column_5"`
	Checksum          string             `json:"checksum"`
	Column7           []byte             `json:"column_7"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertPartnerExportRun(ctx context.Context, arg *InsertPartnerExportRunParams) (*PartnerExportRun, error) {
	row := q.db.QueryRow(ctx, insertPartnerExportRun,
		arg.OrganisationID,
		arg.RequestedByUserID,
		arg.Format,
		arg.Column4,
		arg.Column5,
		arg.Checksum,
		arg.Column7,
		arg.CreatedAt,
	)
	var i PartnerExportRun
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.RequestedByUserID,
		&i.Format,
		&i.Scope,
		&i.RecordCounts,
		&i.Checksum,
		&i.Payload,
		&i.CreatedAt,
	)
	return &i, err
}

const insertPartnerWebhookEvent = `-- name: InsertPartnerWebhookEvent :one
INSERT INTO partner_webhook_events (
    subscription_id,
    event_type,
    payload,
    metadata,
    status,
    attempt_count,
    last_error,
    created_at,
    delivered_at
)
VALUES ($1, $2, $3::jsonb, $4::jsonb, $5, $6, $7, $8, $9)
RETURNING
    id,
    subscription_id,
    event_type,
    payload,
    metadata,
    status,
    attempt_count,
    last_error,
    created_at,
    delivered_at
`

type InsertPartnerWebhookEventParams struct {
	SubscriptionID int64              `json:"subscription_id"`
	EventType      string             `json:"event_type"`
	Column3        []byte             `json:"column_3"`
	Column4        []byte             `json:"column_4"`
	Status         string             `json:"status"`
	AttemptCount   int32              `json:"attempt_count"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) InsertPartnerWebhookEvent(ctx context.Context, arg *InsertPartnerWebhookEventParams) (*PartnerWebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertPartnerWebhookEvent,
		arg.SubscriptionID,
		arg.EventType,
		arg.Column3,
		arg.Column4,
		arg.Status,
		arg.AttemptCount,
		arg.LastError,
		arg.CreatedAt,
		arg.DeliveredAt,
	)
	var i PartnerWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.EventType,
		&i.Payload,
		&i.Metadata,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return &i, err
}

const insertPartnerWebhookSubscription = `-- name: InsertPartnerWebhookSubscription :one
INSERT INTO partner_webhook_subscriptions (
    organisation_id,
    name,
    target_url,
    event_types,
    secret_hash,
    status,
    last_test_metadata,
    created_by_user_id,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4::jsonb, $5, $6, $7::jsonb, $8, $9, $9)
RETURNING
    id,
    organisation_id,
    name,
    target_url,
    event_types,
    secret_hash,
    status,
    last_tested_at,
    last_test_status,
    last_test_metadata,
    last_error,
    created_by_user_id,
    created_at,
    updated_at
`

type InsertPartnerWebhookSubscriptionParams struct {
	OrganisationID  *int64             `json:"organisation_id"`
	Name            string             `json:"name"`
	TargetUrl       string             `json:"target_url"`
	Column4         []byte             `json:"column_4"`
	SecretHash      string             `json:"secret_hash"`
	Status          string             `json:"status"`
	Column7         []byte             `json:"column_7"`
	CreatedByUserID *int64             `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertPartnerWebhookSubscription(ctx context.Context, arg *InsertPartnerWebhookSubscriptionParams) (*PartnerWebhookSubscription, error) {
	row := q.db.QueryRow(ctx, insertPartnerWebhookSubscription,
		arg.OrganisationID,
		arg.Name,
		arg.TargetUrl,
		arg.Column4,
		arg.SecretHash,
		arg.Status,
		arg.Column7,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i PartnerWebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Name,
		&i.TargetUrl,
		&i.EventTypes,
		&i.SecretHash,
		&i.Status,
		&i.LastTestedAt,
		&i.LastTestStatus,
		&i.LastTestMetadata,
		&i.LastError,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listIntegrationStatusChecks = `-- name: ListIntegrationStatusChecks :many
SELECT
    id,
    organisation_id,
    check_name,
    status,
    summary,
    metadata,
    checked_at
FROM integration_status_checks
WHERE $1 IS NULL OR organisation_id = $1
ORDER BY checked_at DESC, id DESC
`

func (q *Queries) ListIntegrationStatusChecks(ctx context.Context, organisationID interface{}) ([]*IntegrationStatusCheck, error) {
	rows, err := q.db.Query(ctx, listIntegrationStatusChecks, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*IntegrationStatusCheck
	for rows.Next() {
		var i IntegrationStatusCheck
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.CheckName,
			&i.Status,
			&i.Summary,
			&i.Metadata,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerAPIKeys = `-- name: ListPartnerAPIKeys :many
SELECT
    id,
    organisation_id,
    name,
    environment,
    key_prefix,
    key_hash,
    scopes,
    allowed_districts,
    expires_at,
    revoked_at,
    last_used_at,
    host(last_used_ip) AS last_used_ip,
    created_by_user_id,
    created_at,
    updated_at
FROM partner_api_keys
WHERE $1 IS NULL OR organisation_id = $1
ORDER BY created_at DESC, id DESC
`

type ListPartnerAPIKeysRow struct {
	ID               int64              `json:"id"`
	OrganisationID   *int64             `json:"organisation_id"`
	Name             string             `json:"name"`
	Environment      string             `json:"environment"`
	KeyPrefix        string             `json:"key_prefix"`
	KeyHash          string             `json:"key_hash"`
	Scopes           []byte             `json:"scopes"`
	AllowedDistricts []byte             `json:"allowed_districts"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	LastUsedIp       string             `json:"last_used_ip"`
	CreatedByUserID  *int64             `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPartnerAPIKeys(ctx context.Context, organisationID interface{}) ([]*ListPartnerAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listPartnerAPIKeys, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPartnerAPIKeysRow
	for rows.Next() {
		var i ListPartnerAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Name,
			&i.Environment,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.AllowedDistricts,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerExportRuns = `-- name: ListPartnerExportRuns :many
SELECT
    id,
    organisation_id,
    requested_by_user_id,
    format,
    scope,
    record_counts,
    checksum,
    payload,
    created_at
FROM partner_export_runs
WHERE $1 IS NULL OR organisation_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPartnerExportRuns(ctx context.Context, organisationID interface{}) ([]*PartnerExportRun, error) {
	rows, err := q.db.Query(ctx, listPartnerExportRuns, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PartnerExportRun
	for rows.Next() {
		var i PartnerExportRun
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.RequestedByUserID,
			&i.Format,
			&i.Scope,
			&i.RecordCounts,
			&i.Checksum,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerWebhookEvents = `-- name: ListPartnerWebhookEvents :many
SELECT
    partner_webhook_events.id,
    partner_webhook_events.subscription_id,
    partner_webhook_events.event_type,
    partner_webhook_events.payload,
    partner_webhook_events.metadata,
    partner_webhook_events.status,
    partner_webhook_events.attempt_count,
    partner_webhook_events.last_error,
    partner_webhook_events.created_at,
    partner_webhook_events.delivered_at
FROM partner_webhook_events
JOIN partner_webhook_subscriptions ON partner_webhook_subscriptions.id = partner_webhook_events.subscription_id
WHERE $1 IS NULL OR partner_webhook_subscriptions.organisation_id = $1
ORDER BY partner_webhook_events.created_at DESC, partner_webhook_events.id DESC
`

func (q *Queries) ListPartnerWebhookEvents(ctx context.Context, organisationID interface{}) ([]*PartnerWebhookEvent, error) {
	rows, err := q.db.Query(ctx, listPartnerWebhookEvents, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PartnerWebhookEvent
	for rows.Next() {
		var i PartnerWebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.EventType,
			&i.Payload,
			&i.Metadata,
			&i.Status,
			&i.AttemptCount,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerWebhookSubscriptions = `-- name: ListPartnerWebhookSubscriptions :many
SELECT
    id,
    organisation_id,
    name,
    target_url,
    event_types,
    secret_hash,
    status,
    last_tested_at,
    last_test_status,
    last_test_metadata,
    last_error,
    created_by_user_id,
    created_at,
    updated_at
FROM partner_webhook_subscriptions
WHERE $1 IS NULL OR organisation_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPartnerWebhookSubscriptions(ctx context.Context, organisationID interface{}) ([]*PartnerWebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listPartnerWebhookSubscriptions, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PartnerWebhookSubscription
	for rows.Next() {
		var i PartnerWebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Name,
			&i.TargetUrl,
			&i.EventTypes,
			&i.SecretHash,
			&i.Status,
			&i.LastTestedAt,
			&i.LastTestStatus,
			&i.LastTestMetadata,
			&i.LastError,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePartnerAPIKey = `-- name: RevokePartnerAPIKey :execrows
UPDATE partner_api_keys
SET
    revoked_at = $2,
    updated_at = $2
WHERE id = $1
    AND revoked_at IS NULL
`

type RevokePartnerAPIKeyParams struct {
	ID        int64              `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokePartnerAPIKey(ctx context.Context, arg *RevokePartnerAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePartnerAPIKey, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchPartnerAPIKey = `-- name: TouchPartnerAPIKey :execrows
UPDATE partner_api_keys
SET
    last_used_at = $3,
    last_used_ip = NULLIF($2, '')::inet,
    updated_at = $3
WHERE id = $1
    AND revoked_at IS NULL
    AND (expires_at IS NULL OR expires_at > $3)
`

type TouchPartnerAPIKeyParams struct {
	ID         int64              `json:"id"`
	Column2    interface{}        `json:"column_2"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) TouchPartnerAPIKey(ctx context.Context, arg *TouchPartnerAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchPartnerAPIKey, arg.ID, arg.Column2, arg.LastUsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertIntegrationStatusCheck = `-- name: UpsertIntegrationStatusCheck :one
INSERT INTO integration_status_checks (
    organisation_id,
    check_name,
    status,
    summary,
    metadata,
    checked_at
)
VALUES ($1, $2, $3, $4, $5::jsonb, $6)
ON CONFLICT ((COALESCE(organisation_id, 0)), check_name) DO UPDATE SET
    status = EXCLUDED.status,
    summary = EXCLUDED.summary,
    metadata = EXCLUDED.metadata,
    checked_at = EXCLUDED.checked_at
RETURNING
    id,
    organisation_id,
    check_name,
    status,
    summary,
    metadata,
    checked_at
`

type UpsertIntegrationStatusCheckParams struct {
	OrganisationID *int64             `json:"organisation_id"`
	CheckName      string             `json:"check_name"`
	Status         string             `json:"status"`
	Summary        string             `json:"summary"`
	Column5        []byte             `json:"column_5"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
}

func (q *Queries) UpsertIntegrationStatusCheck(ctx context.Context, arg *UpsertIntegrationStatusCheckParams) (*IntegrationStatusCheck, error) {
	row := q.db.QueryRow(ctx, upsertIntegrationStatusCheck,
		arg.OrganisationID,
		arg.CheckName,
		arg.Status,
		arg.Summary,
		arg.Column5,
		arg.CheckedAt,
	)
	var i IntegrationStatusCheck
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CheckName,
		&i.Status,
		&i.Summary,
		&i.Metadata,
		&i.CheckedAt,
	)
	return &i, err
}
