// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSession(ctx context.Context, arg *CreateSessionParams) (*CreateSessionRow, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*CreateUserRow, error)
	DeleteOrganisationMembershipsForUser(ctx context.Context, userID int64) error
	DisableUser(ctx context.Context, arg *DisableUserParams) (int64, error)
	EnableUser(ctx context.Context, id int64) (int64, error)
	GetAdminUserAccessByUserID(ctx context.Context, userID int64) (*GetAdminUserAccessByUserIDRow, error)
	GetClinic(ctx context.Context, id string) (*GetClinicRow, error)
	GetClinicDistrict(ctx context.Context, id string) (string, error)
	GetCurrentStatus(ctx context.Context, clinicID string) (*GetCurrentStatusRow, error)
	GetCurrentStatusForUpdate(ctx context.Context, clinicID string) (*GetCurrentStatusForUpdateRow, error)
	GetLatestPartnerExportRun(ctx context.Context, organisationID interface{}) (*PartnerExportRun, error)
	GetPartnerAPIKeyByHash(ctx context.Context, keyHash string) (*GetPartnerAPIKeyByHashRow, error)
	GetPartnerAPIKeyState(ctx context.Context, id int64) (*GetPartnerAPIKeyStateRow, error)
	GetPartnerExportRun(ctx context.Context, id int64) (*PartnerExportRun, error)
	GetPartnerExportRunForOrganisation(ctx context.Context, arg *GetPartnerExportRunForOrganisationParams) (*PartnerExportRun, error)
	GetPendingReportByPayload(ctx context.Context, arg *GetPendingReportByPayloadParams) (*GetPendingReportByPayloadRow, error)
	GetRecentReportByPayload(ctx context.Context, arg *GetRecentReportByPayloadParams) (*GetRecentReportByPayloadRow, error)
	GetReportByExternalID(ctx context.Context, externalID *string) (*GetReportByExternalIDRow, error)
	GetReportForReview(ctx context.Context, id int64) (*GetReportForReviewRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (*GetSessionByTokenHashRow, error)
	GetUserByEmail(ctx context.Context, lower string) (*GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (*GetUserByIDRow, error)
	InsertAuditEvent(ctx context.Context, arg *InsertAuditEventParams) (*AuditEvent, error)
	InsertOrganisationMembership(ctx context.Context, arg *InsertOrganisationMembershipParams) (*InsertOrganisationMembershipRow, error)
	InsertPartnerAPIKey(ctx context.Context, arg *InsertPartnerAPIKeyParams) (*InsertPartnerAPIKeyRow, error)
	InsertPartnerExportRun(ctx context.Context, arg *InsertPartnerExportRunParams) (*PartnerExportRun, error)
	InsertPartnerWebhookEvent(ctx context.Context, arg *InsertPartnerWebhookEventParams) (*PartnerWebhookEvent, error)
	InsertPartnerWebhookSubscription(ctx context.Context, arg *InsertPartnerWebhookSubscriptionParams) (*PartnerWebhookSubscription, error)
	InsertReport(ctx context.Context, arg *InsertReportParams) (*InsertReportRow, error)
	InsertReportReview(ctx context.Context, arg *InsertReportReviewParams) error
	InsertReportSyncAttempt(ctx context.Context, arg *InsertReportSyncAttemptParams) (*ReportSyncAttempt, error)
	ListAdminAuditEvents(ctx context.Context, arg *ListAdminAuditEventsParams) ([]*AuditEvent, error)
	ListAdminUserAccess(ctx context.Context, dollar_1 interface{}) ([]*ListAdminUserAccessRow, error)
	ListClinicAuditEvents(ctx context.Context, clinicID *string) ([]*AuditEvent, error)
	ListClinicReports(ctx context.Context, clinicID string) ([]*ListClinicReportsRow, error)
	ListClinicServices(ctx context.Context, clinicID string) ([]*ListClinicServicesRow, error)
	// clinics
	ListClinics(ctx context.Context) ([]*ListClinicsRow, error)
	ListCurrentStatuses(ctx context.Context) ([]*ListCurrentStatusesRow, error)
	ListCurrentStatusesForReviewScope(ctx context.Context, arg *ListCurrentStatusesForReviewScopeParams) ([]*ListCurrentStatusesForReviewScopeRow, error)
	ListIntegrationStatusChecks(ctx context.Context, organisationID interface{}) ([]*IntegrationStatusCheck, error)
	ListMembershipsForUser(ctx context.Context, userID int64) ([]*ListMembershipsForUserRow, error)
	ListPartnerAPIKeys(ctx context.Context, organisationID interface{}) ([]*ListPartnerAPIKeysRow, error)
	ListPartnerExportRuns(ctx context.Context, organisationID interface{}) ([]*PartnerExportRun, error)
	ListPartnerWebhookEvents(ctx context.Context, organisationID interface{}) ([]*PartnerWebhookEvent, error)
	ListPartnerWebhookSubscriptions(ctx context.Context, organisationID interface{}) ([]*PartnerWebhookSubscription, error)
	ListPendingReports(ctx context.Context, arg *ListPendingReportsParams) ([]*ListPendingReportsRow, error)
	ListPilotIngestionRuns(ctx context.Context, arg *ListPilotIngestionRunsParams) ([]*PilotIngestionRun, error)
	LockUserForMembershipReplacement(ctx context.Context, id int64) (int64, error)
	RevokeActiveSessionsForUser(ctx context.Context, userID int64) (int64, error)
	RevokePartnerAPIKey(ctx context.Context, arg *RevokePartnerAPIKeyParams) (int64, error)
	RevokeSession(ctx context.Context, tokenHash string) error
	SyncSummarySince(ctx context.Context, receivedAt pgtype.Timestamptz) (*SyncSummarySinceRow, error)
	SyncSummarySinceForReviewScope(ctx context.Context, arg *SyncSummarySinceForReviewScopeParams) (*SyncSummarySinceForReviewScopeRow, error)
	TouchPartnerAPIKey(ctx context.Context, arg *TouchPartnerAPIKeyParams) (int64, error)
	UpdateCurrentStatusFreshness(ctx context.Context, arg *UpdateCurrentStatusFreshnessParams) (*UpdateCurrentStatusFreshnessRow, error)
	UpdateReportReviewState(ctx context.Context, arg *UpdateReportReviewStateParams) (*UpdateReportReviewStateRow, error)
	UpdateUserLifecycle(ctx context.Context, arg *UpdateUserLifecycleParams) (*UpdateUserLifecycleRow, error)
	UpdateUserLifecycleName(ctx context.Context, arg *UpdateUserLifecycleNameParams) (*UpdateUserLifecycleNameRow, error)
	UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) (*UpdateUserPasswordRow, error)
	UpsertCurrentStatus(ctx context.Context, arg *UpsertCurrentStatusParams) (*UpsertCurrentStatusRow, error)
	UpsertIntegrationStatusCheck(ctx context.Context, arg *UpsertIntegrationStatusCheckParams) (*IntegrationStatusCheck, error)
	VerifyClinicExists(ctx context.Context, id string) (string, error)
}

var _ Querier = (*Queries)(nil)
