// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPendingReportByPayload = `-- name: GetPendingReportByPayload :one
SELECT
    id,
    external_id,
    clinic_id,
    reporter_name,
    source,
    offline_created,
    submitted_at,
    received_at,
    status,
    reason,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    notes,
    review_state,
    confidence_score::double precision,
    visit_verification,
    submitted_by_user_id,
    reviewed_by_user_id,
    reviewed_at,
    review_notes
FROM reports
WHERE review_state = 'pending'
    AND clinic_id = $1
    AND source = $2
    AND status = $3
    AND reason IS NOT DISTINCT FROM $4::text
    AND staff_pressure IS NOT DISTINCT FROM $5::text
    AND stock_pressure IS NOT DISTINCT FROM $6::text
    AND queue_pressure IS NOT DISTINCT FROM $7::text
    AND submitted_by_user_id IS NOT DISTINCT FROM $8::bigint
ORDER BY received_at DESC, id DESC
LIMIT 1
`

type GetPendingReportByPayloadParams struct {
	ClinicID string `json:"clinic_id"`
	Source   string `json:"source"`
	Status   string `json:"status"`
	Column4  string `json:"column_4"`
	Column5  string `json:"column_5"`
	Column6  string `json:"column_6"`
	Column7  string `json:"column_7"`
	Column8  int64  `json:"column_8"`
}

type GetPendingReportByPayloadRow struct {
	ID                int64              `json:"id"`
	ExternalID        *string            `json:"external_id"`
	ClinicID          string             `json:"clinic_id"`
	ReporterName      *string            `json:"reporter_name"`
	Source            string             `json:"source"`
	OfflineCreated    bool               `json:"offline_created"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	Status            string             `json:"status"`
	Reason            *string            `json:"reason"`
	StaffPressure     *string            `json:"staff_pressure"`
	StockPressure     *string            `json:"stock_pressure"`
	QueuePressure     *string            `json:"queue_pressure"`
	Notes             *string            `json:"notes"`
	ReviewState       string             `json:"review_state"`
	ConfidenceScore   float64            `json:"confidence_score"`
	VisitVerification []byte             `json:"visit_verification"`
	SubmittedByUserID *int64             `json:"submitted_by_user_id"`
	ReviewedByUserID  *int64             `json:"reviewed_by_user_id"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes       *string            `json:"review_notes"`
}

func (q *Queries) GetPendingReportByPayload(ctx context.Context, arg *GetPendingReportByPayloadParams) (*GetPendingReportByPayloadRow, error) {
	row := q.db.QueryRow(ctx, getPendingReportByPayload,
		arg.ClinicID,
		arg.Source,
		arg.Status,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	var i GetPendingReportByPayloadRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ClinicID,
		&i.ReporterName,
		&i.Source,
		&i.OfflineCreated,
		&i.SubmittedAt,
		&i.ReceivedAt,
		&i.Status,
		&i.Reason,
		&i.StaffPressure,
		&i.StockPressure,
		&i.QueuePressure,
		&i.Notes,
		&i.ReviewState,
		&i.ConfidenceScore,
		&i.VisitVerification,
		&i.SubmittedByUserID,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.ReviewNotes,
	)
	return &i, err
}

const getRecentReportByPayload = `-- name: GetRecentReportByPayload :one
SELECT
    id,
    external_id,
    clinic_id,
    reporter_name,
    source,
    offline_created,
    submitted_at,
    received_at,
    status,
    reason,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    notes,
    review_state,
    confidence_score::double precision,
    visit_verification,
    submitted_by_user_id,
    reviewed_by_user_id,
    reviewed_at,
    review_notes
FROM reports
WHERE received_at >= $9
    AND clinic_id = $1
    AND source = $2
    AND status = $3
    AND reason IS NOT DISTINCT FROM $4::text
    AND staff_pressure IS NOT DISTINCT FROM $5::text
    AND stock_pressure IS NOT DISTINCT FROM $6::text
    AND queue_pressure IS NOT DISTINCT FROM $7::text
    AND submitted_by_user_id IS NOT DISTINCT FROM $8::bigint
ORDER BY received_at DESC, id DESC
LIMIT 1
`

type GetRecentReportByPayloadParams struct {
	ClinicID   string             `json:"clinic_id"`
	Source     string             `json:"source"`
	Status     string             `json:"status"`
	Column4    string             `json:"column_4"`
	Column5    string             `json:"column_5"`
	Column6    string             `json:"column_6"`
	Column7    string             `json:"column_7"`
	Column8    int64              `json:"column_8"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type GetRecentReportByPayloadRow struct {
	ID                int64              `json:"id"`
	ExternalID        *string            `json:"external_id"`
	ClinicID          string             `json:"clinic_id"`
	ReporterName      *string            `json:"reporter_name"`
	Source            string             `json:"source"`
	OfflineCreated    bool               `json:"offline_created"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	Status            string             `json:"status"`
	Reason            *string            `json:"reason"`
	StaffPressure     *string            `json:"staff_pressure"`
	StockPressure     *string            `json:"stock_pressure"`
	QueuePressure     *string            `json:"queue_pressure"`
	Notes             *string            `json:"notes"`
	ReviewState       string             `json:"review_state"`
	ConfidenceScore   float64            `json:"confidence_score"`
	VisitVerification []byte             `json:"visit_verification"`
	SubmittedByUserID *int64             `json:"submitted_by_user_id"`
	ReviewedByUserID  *int64             `json:"reviewed_by_user_id"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes       *string            `json:"review_notes"`
}

func (q *Queries) GetRecentReportByPayload(ctx context.Context, arg *GetRecentReportByPayloadParams) (*GetRecentReportByPayloadRow, error) {
	row := q.db.QueryRow(ctx, getRecentReportByPayload,
		arg.ClinicID,
		arg.Source,
		arg.Status,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.ReceivedAt,
	)
	var i GetRecentReportByPayloadRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ClinicID,
		&i.ReporterName,
		&i.Source,
		&i.OfflineCreated,
		&i.SubmittedAt,
		&i.ReceivedAt,
		&i.Status,
		&i.Reason,
		&i.StaffPressure,
		&i.StockPressure,
		&i.QueuePressure,
		&i.Notes,
		&i.ReviewState,
		&i.ConfidenceScore,
		&i.VisitVerification,
		&i.SubmittedByUserID,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.ReviewNotes,
	)
	return &i, err
}

const getReportByExternalID = `-- name: GetReportByExternalID :one
SELECT
    id,
    external_id,
    clinic_id,
    reporter_name,
    source,
    offline_created,
    submitted_at,
    received_at,
    status,
    reason,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    notes,
    review_state,
    confidence_score::double precision,
    visit_verification,
    submitted_by_user_id,
    reviewed_by_user_id,
    reviewed_at,
    review_notes
FROM reports
WHERE external_id = $1
`

type GetReportByExternalIDRow struct {
	ID                int64              `json:"id"`
	ExternalID        *string            `json:"external_id"`
	ClinicID          string             `json:"clinic_id"`
	ReporterName      *string            `json:"reporter_name"`
	Source            string             `json:"source"`
	OfflineCreated    bool               `json:"offline_created"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	Status            string             `json:"status"`
	Reason            *string            `json:"reason"`
	StaffPressure     *string            `json:"staff_pressure"`
	StockPressure     *string            `json:"stock_pressure"`
	QueuePressure     *string            `json:"queue_pressure"`
	Notes             *string            `json:"notes"`
	ReviewState       string             `json:"review_state"`
	ConfidenceScore   float64            `json:"confidence_score"`
	VisitVerification []byte             `json:"visit_verification"`
	SubmittedByUserID *int64             `json:"submitted_by_user_id"`
	ReviewedByUserID  *int64             `json:"reviewed_by_user_id"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes       *string            `json:"review_notes"`
}

func (q *Queries) GetReportByExternalID(ctx context.Context, externalID *string) (*GetReportByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getReportByExternalID, externalID)
	var i GetReportByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ClinicID,
		&i.ReporterName,
		&i.Source,
		&i.OfflineCreated,
		&i.SubmittedAt,
		&i.ReceivedAt,
		&i.Status,
		&i.Reason,
		&i.StaffPressure,
		&i.StockPressure,
		&i.QueuePressure,
		&i.Notes,
		&i.ReviewState,
		&i.ConfidenceScore,
		&i.VisitVerification,
		&i.SubmittedByUserID,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.ReviewNotes,
	)
	return &i, err
}

const getReportForReview = `-- name: GetReportForReview :one
SELECT
    id,
    external_id,
    clinic_id,
    reporter_name,
    source,
    offline_created,
    submitted_at,
    received_at,
    status,
    reason,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    notes,
    review_state,
    confidence_score::double precision,
    visit_verification,
    submitted_by_user_id,
    reviewed_by_user_id,
    reviewed_at,
    review_notes
FROM reports
WHERE id = $1
FOR UPDATE
`

type GetReportForReviewRow struct {
	ID                int64              `json:"id"`
	ExternalID        *string            `json:"external_id"`
	ClinicID          string             `json:"clinic_id"`
	ReporterName      *string            `json:"reporter_name"`
	Source            string             `json:"source"`
	OfflineCreated    bool               `json:"offline_created"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	Status            string             `json:"status"`
	Reason            *string            `json:"reason"`
	StaffPressure     *string            `json:"staff_pressure"`
	StockPressure     *string            `json:"stock_pressure"`
	QueuePressure     *string            `json:"queue_pressure"`
	Notes             *string            `json:"notes"`
	ReviewState       string             `json:"review_state"`
	ConfidenceScore   float64            `json:"confidence_score"`
	VisitVerification []byte             `json:"visit_verification"`
	SubmittedByUserID *int64             `json:"submitted_by_user_id"`
	ReviewedByUserID  *int64             `json:"reviewed_by_user_id"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes       *string            `json:"review_notes"`
}

func (q *Queries) GetReportForReview(ctx context.Context, id int64) (*GetReportForReviewRow, error) {
	row := q.db.QueryRow(ctx, getReportForReview, id)
	var i GetReportForReviewRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ClinicID,
		&i.ReporterName,
		&i.Source,
		&i.OfflineCreated,
		&i.SubmittedAt,
		&i.ReceivedAt,
		&i.Status,
		&i.Reason,
		&i.StaffPressure,
		&i.StockPressure,
		&i.QueuePressure,
		&i.Notes,
		&i.ReviewState,
		&i.ConfidenceScore,
		&i.VisitVerification,
		&i.SubmittedByUserID,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.ReviewNotes,
	)
	return &i, err
}

const insertReport = `-- name: InsertReport :one
INSERT INTO reports (
    external_id,
    clinic_id,
    reporter_name,
    source,
    offline_created,
    submitted_at,
    received_at,
    status,
    reason,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    notes,
    review_state,
    confidence_score,
    visit_verification,
    submitted_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING
    id,
    external_id,
    clinic_id,
    reporter_name,
    source,
    offline_created,
    submitted_at,
    received_at,
    status,
    reason,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    notes,
    review_state,
    confidence_score::double precision,
    visit_verification,
    submitted_by_user_id,
    reviewed_by_user_id,
    reviewed_at,
    review_notes
`

type InsertReportParams struct {
	ExternalID        *string            `json:"external_id"`
	ClinicID          string             `json:"clinic_id"`
	ReporterName      *string            `json:"reporter_name"`
	Source            string             `json:"source"`
	OfflineCreated    bool               `json:"offline_created"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	Status            string             `json:"status"`
	Reason            *string            `json:"reason"`
	StaffPressure     *string            `json:"staff_pressure"`
	StockPressure     *string            `json:"stock_pressure"`
	QueuePressure     *string            `json:"queue_pressure"`
	Notes             *string            `json:"notes"`
	ReviewState       string             `json:"review_state"`
	ConfidenceScore   pgtype.Numeric     `json:"confidence_score"`
	VisitVerification []byte             `json:"visit_verification"`
	SubmittedByUserID *int64             `json:"submitted_by_user_id"`
}

type InsertReportRow struct {
	ID                int64              `json:"id"`
	ExternalID        *string            `json:"external_id"`
	ClinicID          string             `json:"clinic_id"`
	ReporterName      *string            `json:"reporter_name"`
	Source            string             `json:"source"`
	OfflineCreated    bool               `json:"offline_created"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	Status            string             `json:"status"`
	Reason            *string            `json:"reason"`
	StaffPressure     *string            `json:"staff_pressure"`
	StockPressure     *string            `json:"stock_pressure"`
	QueuePressure     *string            `json:"queue_pressure"`
	Notes             *string            `json:"notes"`
	ReviewState       string             `json:"review_state"`
	ConfidenceScore   float64            `json:"confidence_score"`
	VisitVerification []byte             `json:"visit_verification"`
	SubmittedByUserID *int64             `json:"submitted_by_user_id"`
	ReviewedByUserID  *int64             `json:"reviewed_by_user_id"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes       *string            `json:"review_notes"`
}

func (q *Queries) InsertReport(ctx context.Context, arg *InsertReportParams) (*InsertReportRow, error) {
	row := q.db.QueryRow(ctx, insertReport,
		arg.ExternalID,
		arg.ClinicID,
		arg.ReporterName,
		arg.Source,
		arg.OfflineCreated,
		arg.SubmittedAt,
		arg.ReceivedAt,
		arg.Status,
		arg.Reason,
		arg.StaffPressure,
		arg.StockPressure,
		arg.QueuePressure,
		arg.Notes,
		arg.ReviewState,
		arg.ConfidenceScore,
		arg.VisitVerification,
		arg.SubmittedByUserID,
	)
	var i InsertReportRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ClinicID,
		&i.ReporterName,
		&i.Source,
		&i.OfflineCreated,
		&i.SubmittedAt,
		&i.ReceivedAt,
		&i.Status,
		&i.Reason,
		&i.StaffPressure,
		&i.StockPressure,
		&i.QueuePressure,
		&i.Notes,
		&i.ReviewState,
		&i.ConfidenceScore,
		&i.VisitVerification,
		&i.SubmittedByUserID,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.ReviewNotes,
	)
	return &i, err
}

const insertReportReview = `-- name: InsertReportReview :exec
INSERT INTO report_reviews (
    report_id,
    reviewer_user_id,
    organisation_id,
    decision,
    notes,
    metadata,
    created_at
)
VALUES ($1, $2, $3, $4, $5, '{}'::jsonb, $6)
`

type InsertReportReviewParams struct {
	ReportID       int64              `json:"report_id"`
	ReviewerUserID int64              `json:"reviewer_user_id"`
	OrganisationID *int64             `json:"organisation_id"`
	Decision       string             `json:"decision"`
	Notes          *string            `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertReportReview(ctx context.Context, arg *InsertReportReviewParams) error {
	_, err := q.db.Exec(ctx, insertReportReview,
		arg.ReportID,
		arg.ReviewerUserID,
		arg.OrganisationID,
		arg.Decision,
		arg.Notes,
		arg.CreatedAt,
	)
	return err
}

const listClinicReports = `-- name: ListClinicReports :many
SELECT
    id,
    external_id,
    clinic_id,
    reporter_name,
    source,
    offline_created,
    submitted_at,
    received_at,
    status,
    reason,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    notes,
    review_state,
    confidence_score::double precision,
    visit_verification,
    submitted_by_user_id,
    reviewed_by_user_id,
    reviewed_at,
    review_notes
FROM reports
WHERE clinic_id = $1
ORDER BY received_at DESC, id DESC
`

type ListClinicReportsRow struct {
	ID                int64              `json:"id"`
	ExternalID        *string            `json:"external_id"`
	ClinicID          string             `json:"clinic_id"`
	ReporterName      *string            `json:"reporter_name"`
	Source            string             `json:"source"`
	OfflineCreated    bool               `json:"offline_created"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	Status            string             `json:"status"`
	Reason            *string            `json:"reason"`
	StaffPressure     *string            `json:"staff_pressure"`
	StockPressure     *string            `json:"stock_pressure"`
	QueuePressure     *string            `json:"queue_pressure"`
	Notes             *string            `json:"notes"`
	ReviewState       string             `json:"review_state"`
	ConfidenceScore   float64            `json:"confidence_score"`
	VisitVerification []byte             `json:"visit_verification"`
	SubmittedByUserID *int64             `json:"submitted_by_user_id"`
	ReviewedByUserID  *int64             `json:"reviewed_by_user_id"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes       *string            `json:"review_notes"`
}

func (q *Queries) ListClinicReports(ctx context.Context, clinicID string) ([]*ListClinicReportsRow, error) {
	rows, err := q.db.Query(ctx, listClinicReports, clinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListClinicReportsRow
	for rows.Next() {
		var i ListClinicReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.ClinicID,
			&i.ReporterName,
			&i.Source,
			&i.OfflineCreated,
			&i.SubmittedAt,
			&i.ReceivedAt,
			&i.Status,
			&i.Reason,
			&i.StaffPressure,
			&i.StockPressure,
			&i.QueuePressure,
			&i.Notes,
			&i.ReviewState,
			&i.ConfidenceScore,
			&i.VisitVerification,
			&i.SubmittedByUserID,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.ReviewNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReports = `-- name: ListPendingReports :many
SELECT
    reports.id,
    reports.external_id,
    reports.clinic_id,
    reports.reporter_name,
    reports.source,
    reports.offline_created,
    reports.submitted_at,
    reports.received_at,
    reports.status,
    reports.reason,
    reports.staff_pressure,
    reports.stock_pressure,
    reports.queue_pressure,
    reports.notes,
    reports.review_state,
    reports.confidence_score::double precision,
    reports.visit_verification,
    reports.submitted_by_user_id,
    reports.reviewed_by_user_id,
    reports.reviewed_at,
    reports.review_notes
FROM reports
JOIN clinics ON clinics.id = reports.clinic_id
WHERE reports.review_state = 'pending'
    AND (
        ($1 = 'district_manager' AND $2::text IS NOT NULL AND clinics.district = $2)
        OR $1 IN ('org_admin', 'system_admin')
    )
ORDER BY reports.received_at DESC, reports.id DESC
`

type ListPendingReportsParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 string      `json:"column_2"`
}

type ListPendingReportsRow struct {
	ID                     int64              `json:"id"`
	ExternalID             *string            `json:"external_id"`
	ClinicID               string             `json:"clinic_id"`
	ReporterName           *string            `json:"reporter_name"`
	Source                 string             `json:"source"`
	OfflineCreated         bool               `json:"offline_created"`
	SubmittedAt            pgtype.Timestamptz `json:"submitted_at"`
	ReceivedAt             pgtype.Timestamptz `json:"received_at"`
	Status                 string             `json:"status"`
	Reason                 *string            `json:"reason"`
	StaffPressure          *string            `json:"staff_pressure"`
	StockPressure          *string            `json:"stock_pressure"`
	QueuePressure          *string            `json:"queue_pressure"`
	Notes                  *string            `json:"notes"`
	ReviewState            string             `json:"review_state"`
	ReportsConfidenceScore float64            `json:"reports_confidence_score"`
	VisitVerification      []byte             `json:"visit_verification"`
	SubmittedByUserID      *int64             `json:"submitted_by_user_id"`
	ReviewedByUserID       *int64             `json:"reviewed_by_user_id"`
	ReviewedAt             pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes            *string            `json:"review_notes"`
}

func (q *Queries) ListPendingReports(ctx context.Context, arg *ListPendingReportsParams) ([]*ListPendingReportsRow, error) {
	rows, err := q.db.Query(ctx, listPendingReports, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPendingReportsRow
	for rows.Next() {
		var i ListPendingReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.ClinicID,
			&i.ReporterName,
			&i.Source,
			&i.OfflineCreated,
			&i.SubmittedAt,
			&i.ReceivedAt,
			&i.Status,
			&i.Reason,
			&i.StaffPressure,
			&i.StockPressure,
			&i.QueuePressure,
			&i.Notes,
			&i.ReviewState,
			&i.ReportsConfidenceScore,
			&i.VisitVerification,
			&i.SubmittedByUserID,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.ReviewNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportReviewState = `-- name: UpdateReportReviewState :one
UPDATE reports
SET
    review_state = $2,
    reviewed_by_user_id = $3,
    reviewed_at = $4,
    review_notes = $5
WHERE id = $1
RETURNING
    id,
    external_id,
    clinic_id,
    reporter_name,
    source,
    offline_created,
    submitted_at,
    received_at,
    status,
    reason,
    staff_pressure,
    stock_pressure,
    queue_pressure,
    notes,
    review_state,
    confidence_score::double precision,
    visit_verification,
    submitted_by_user_id,
    reviewed_by_user_id,
    reviewed_at,
    review_notes
`

type UpdateReportReviewStateParams struct {
	ID               int64              `json:"id"`
	ReviewState      string             `json:"review_state"`
	ReviewedByUserID *int64             `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes      *string            `json:"review_notes"`
}

type UpdateReportReviewStateRow struct {
	ID                int64              `json:"id"`
	ExternalID        *string            `json:"external_id"`
	ClinicID          string             `json:"clinic_id"`
	ReporterName      *string            `json:"reporter_name"`
	Source            string             `json:"source"`
	OfflineCreated    bool               `json:"offline_created"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	Status            string             `json:"status"`
	Reason            *string            `json:"reason"`
	StaffPressure     *string            `json:"staff_pressure"`
	StockPressure     *string            `json:"stock_pressure"`
	QueuePressure     *string            `json:"queue_pressure"`
	Notes             *string            `json:"notes"`
	ReviewState       string             `json:"review_state"`
	ConfidenceScore   float64            `json:"confidence_score"`
	VisitVerification []byte             `json:"visit_verification"`
	SubmittedByUserID *int64             `json:"submitted_by_user_id"`
	ReviewedByUserID  *int64             `json:"reviewed_by_user_id"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes       *string            `json:"review_notes"`
}

func (q *Queries) UpdateReportReviewState(ctx context.Context, arg *UpdateReportReviewStateParams) (*UpdateReportReviewStateRow, error) {
	row := q.db.QueryRow(ctx, updateReportReviewState,
		arg.ID,
		arg.ReviewState,
		arg.ReviewedByUserID,
		arg.ReviewedAt,
		arg.ReviewNotes,
	)
	var i UpdateReportReviewStateRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ClinicID,
		&i.ReporterName,
		&i.Source,
		&i.OfflineCreated,
		&i.SubmittedAt,
		&i.ReceivedAt,
		&i.Status,
		&i.Reason,
		&i.StaffPressure,
		&i.StockPressure,
		&i.QueuePressure,
		&i.Notes,
		&i.ReviewState,
		&i.ConfidenceScore,
		&i.VisitVerification,
		&i.SubmittedByUserID,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.ReviewNotes,
	)
	return &i, err
}
