// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertReportSyncAttempt = `-- name: InsertReportSyncAttempt :one
INSERT INTO report_sync_attempts (
    external_id,
    report_id,
    submitted_by_user_id,
    organisation_id,
    clinic_id,
    result,
    client_attempt_count,
    queued_at,
    submitted_at,
    received_at,
    error_code,
    error_message,
    metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13::jsonb)
RETURNING
    id,
    external_id,
    report_id,
    submitted_by_user_id,
    organisation_id,
    clinic_id,
    result,
    client_attempt_count,
    queued_at,
    submitted_at,
    received_at,
    error_code,
    error_message,
    metadata
`

type InsertReportSyncAttemptParams struct {
	ExternalID         string             `json:"external_id"`
	ReportID           *int64             `json:"report_id"`
	SubmittedByUserID  *int64             `json:"submitted_by_user_id"`
	OrganisationID     *int64             `json:"organisation_id"`
	ClinicID           *string            `json:"clinic_id"`
	Result             string             `json:"result"`
	ClientAttemptCount int32              `json:"client_attempt_count"`
	QueuedAt           pgtype.Timestamptz `json:"queued_at"`
	SubmittedAt        pgtype.Timestamptz `json:"submitted_at"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ErrorCode          *string            `json:"error_code"`
	ErrorMessage       *string            `json:"error_message"`
	Column13           []byte             `json:"column_13"`
}

func (q *Queries) InsertReportSyncAttempt(ctx context.Context, arg *InsertReportSyncAttemptParams) (*ReportSyncAttempt, error) {
	row := q.db.QueryRow(ctx, insertReportSyncAttempt,
		arg.ExternalID,
		arg.ReportID,
		arg.SubmittedByUserID,
		arg.OrganisationID,
		arg.ClinicID,
		arg.Result,
		arg.ClientAttemptCount,
		arg.QueuedAt,
		arg.SubmittedAt,
		arg.ReceivedAt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Column13,
	)
	var i ReportSyncAttempt
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ReportID,
		&i.SubmittedByUserID,
		&i.OrganisationID,
		&i.ClinicID,
		&i.Result,
		&i.ClientAttemptCount,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.ReceivedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
	)
	return &i, err
}

const syncSummarySince = `-- name: SyncSummarySince :one
WITH attempt_counts AS (
    SELECT
        (COUNT(*) FILTER (WHERE report_sync_attempts.result = 'created'))::int AS created_count,
        (COUNT(*) FILTER (WHERE report_sync_attempts.result = 'duplicate'))::int AS duplicate_count,
        (COUNT(*) FILTER (WHERE report_sync_attempts.result = 'conflict'))::int AS conflict_count,
        (COUNT(*) FILTER (WHERE report_sync_attempts.result = 'validation_error'))::int AS validation_error_count
    FROM report_sync_attempts
    WHERE report_sync_attempts.received_at >= $1
),
pending_offline AS (
    SELECT COUNT(*)::int AS pending_count
    FROM reports
    WHERE reports.offline_created = true
        AND reports.review_state = 'pending'
        AND reports.received_at >= $1
),
current_status_counts AS (
    SELECT
        (COUNT(*) FILTER (WHERE current_status.freshness = 'needs_confirmation'))::int AS needs_confirmation_count,
        (COUNT(*) FILTER (WHERE current_status.freshness = 'stale'))::int AS stale_count
    FROM current_status
),
median_status_age AS (
    SELECT
        percentile_cont(0.5) WITHIN GROUP (
            ORDER BY EXTRACT(EPOCH FROM (now() - COALESCE(current_status.last_reported_at, current_status.updated_at))) / 3600.0
        )::double precision AS median_current_status_age_hours
    FROM current_status
)
SELECT
    created_count,
    duplicate_count,
    conflict_count,
    validation_error_count,
    pending_count,
    needs_confirmation_count,
    stale_count,
    median_current_status_age_hours
FROM attempt_counts, pending_offline, current_status_counts, median_status_age
`

type SyncSummarySinceRow struct {
	CreatedCount                int32   `json:"created_count"`
	DuplicateCount              int32   `json:"duplicate_count"`
	ConflictCount               int32   `json:"conflict_count"`
	ValidationErrorCount        int32   `json:"validation_error_count"`
	PendingCount                int32   `json:"pending_count"`
	NeedsConfirmationCount      int32   `json:"needs_confirmation_count"`
	StaleCount                  int32   `json:"stale_count"`
	MedianCurrentStatusAgeHours float64 `json:"median_current_status_age_hours"`
}

func (q *Queries) SyncSummarySince(ctx context.Context, receivedAt pgtype.Timestamptz) (*SyncSummarySinceRow, error) {
	row := q.db.QueryRow(ctx, syncSummarySince, receivedAt)
	var i SyncSummarySinceRow
	err := row.Scan(
		&i.CreatedCount,
		&i.DuplicateCount,
		&i.ConflictCount,
		&i.ValidationErrorCount,
		&i.PendingCount,
		&i.NeedsConfirmationCount,
		&i.StaleCount,
		&i.MedianCurrentStatusAgeHours,
	)
	return &i, err
}

const syncSummarySinceForReviewScope = `-- name: SyncSummarySinceForReviewScope :one
WITH attempt_counts AS (
    SELECT
        (COUNT(*) FILTER (WHERE report_sync_attempts.result = 'created'))::int AS created_count,
        (COUNT(*) FILTER (WHERE report_sync_attempts.result = 'duplicate'))::int AS duplicate_count,
        (COUNT(*) FILTER (WHERE report_sync_attempts.result = 'conflict'))::int AS conflict_count,
        (COUNT(*) FILTER (WHERE report_sync_attempts.result = 'validation_error'))::int AS validation_error_count
    FROM report_sync_attempts
    LEFT JOIN clinics ON clinics.id = report_sync_attempts.clinic_id
    WHERE report_sync_attempts.received_at >= $1
        AND (
            ($2 = 'reporter' AND $4::bigint IS NOT NULL AND report_sync_attempts.submitted_by_user_id = $4)
            OR
            (
                report_sync_attempts.clinic_id IS NOT NULL
                AND ($2 = 'district_manager' AND $3::text IS NOT NULL AND clinics.district = $3)
            )
            OR $2 IN ('org_admin', 'system_admin')
        )
),
pending_offline AS (
    SELECT COUNT(*)::int AS pending_count
    FROM reports
    JOIN clinics ON clinics.id = reports.clinic_id
    WHERE reports.offline_created = true
        AND reports.review_state = 'pending'
        AND reports.received_at >= $1
        AND (
            ($2 = 'reporter' AND $4::bigint IS NOT NULL AND reports.submitted_by_user_id = $4)
            OR ($2 = 'district_manager' AND $3::text IS NOT NULL AND clinics.district = $3)
            OR $2 IN ('org_admin', 'system_admin')
        )
),
current_status_counts AS (
    SELECT
        (COUNT(*) FILTER (WHERE current_status.freshness = 'needs_confirmation'))::int AS needs_confirmation_count,
        (COUNT(*) FILTER (WHERE current_status.freshness = 'stale'))::int AS stale_count
    FROM current_status
    JOIN clinics ON clinics.id = current_status.clinic_id
    WHERE (
        (
            $2 = 'reporter'
            AND $4::bigint IS NOT NULL
            AND (
                EXISTS (
                    SELECT 1
                    FROM report_sync_attempts reporter_attempts
                    WHERE reporter_attempts.submitted_by_user_id = $4
                        AND reporter_attempts.clinic_id = current_status.clinic_id
                        AND reporter_attempts.received_at >= $1
                )
                OR EXISTS (
                    SELECT 1
                    FROM reports reporter_reports
                    WHERE reporter_reports.submitted_by_user_id = $4
                        AND reporter_reports.clinic_id = current_status.clinic_id
                        AND reporter_reports.received_at >= $1
                )
            )
        )
        OR ($2 = 'district_manager' AND $3::text IS NOT NULL AND clinics.district = $3)
        OR $2 IN ('org_admin', 'system_admin')
    )
),
median_status_age AS (
    SELECT
        percentile_cont(0.5) WITHIN GROUP (
            ORDER BY EXTRACT(EPOCH FROM (now() - COALESCE(current_status.last_reported_at, current_status.updated_at))) / 3600.0
        )::double precision AS median_current_status_age_hours
    FROM current_status
    JOIN clinics ON clinics.id = current_status.clinic_id
    WHERE (
        (
            $2 = 'reporter'
            AND $4::bigint IS NOT NULL
            AND (
                EXISTS (
                    SELECT 1
                    FROM report_sync_attempts reporter_attempts
                    WHERE reporter_attempts.submitted_by_user_id = $4
                        AND reporter_attempts.clinic_id = current_status.clinic_id
                        AND reporter_attempts.received_at >= $1
                )
                OR EXISTS (
                    SELECT 1
                    FROM reports reporter_reports
                    WHERE reporter_reports.submitted_by_user_id = $4
                        AND reporter_reports.clinic_id = current_status.clinic_id
                        AND reporter_reports.received_at >= $1
                )
            )
        )
        OR ($2 = 'district_manager' AND $3::text IS NOT NULL AND clinics.district = $3)
        OR $2 IN ('org_admin', 'system_admin')
    )
)
SELECT
    created_count,
    duplicate_count,
    conflict_count,
    validation_error_count,
    pending_count,
    needs_confirmation_count,
    stale_count,
    median_current_status_age_hours
FROM attempt_counts, pending_offline, current_status_counts, median_status_age
`

type SyncSummarySinceForReviewScopeParams struct {
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	Column2    interface{}        `json:"column_2"`
	Column3    string             `json:"column_3"`
	Column4    int64              `json:"column_4"`
}

type SyncSummarySinceForReviewScopeRow struct {
	CreatedCount                int32   `json:"created_count"`
	DuplicateCount              int32   `json:"duplicate_count"`
	ConflictCount               int32   `json:"conflict_count"`
	ValidationErrorCount        int32   `json:"validation_error_count"`
	PendingCount                int32   `json:"pending_count"`
	NeedsConfirmationCount      int32   `json:"needs_confirmation_count"`
	StaleCount                  int32   `json:"stale_count"`
	MedianCurrentStatusAgeHours float64 `json:"median_current_status_age_hours"`
}

func (q *Queries) SyncSummarySinceForReviewScope(ctx context.Context, arg *SyncSummarySinceForReviewScopeParams) (*SyncSummarySinceForReviewScopeRow, error) {
	row := q.db.QueryRow(ctx, syncSummarySinceForReviewScope,
		arg.ReceivedAt,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var i SyncSummarySinceForReviewScopeRow
	err := row.Scan(
		&i.CreatedCount,
		&i.DuplicateCount,
		&i.ConflictCount,
		&i.ValidationErrorCount,
		&i.PendingCount,
		&i.NeedsConfirmationCount,
		&i.StaleCount,
		&i.MedianCurrentStatusAgeHours,
	)
	return &i, err
}
