// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: walkthrough.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWalkthroughRequest = `-- name: CreateWalkthroughRequest :one
INSERT INTO walkthrough_requests (
    name, work_email, organization, role, interest,
    note, requested_date, requested_time, duration_minutes
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
) RETURNING id, name, work_email, organization, role, interest, note, requested_date, requested_time, duration_minutes, status, created_at
`

type CreateWalkthroughRequestParams struct {
	Name            string      `json:"name"`
	WorkEmail       string      `json:"work_email"`
	Organization    string      `json:"organization"`
	Role            string      `json:"role"`
	Interest        string      `json:"interest"`
	Note            string      `json:"note"`
	RequestedDate   pgtype.Date `json:"requested_date"`
	RequestedTime   string      `json:"requested_time"`
	DurationMinutes int32       `json:"duration_minutes"`
}

func (q *Queries) CreateWalkthroughRequest(ctx context.Context, arg *CreateWalkthroughRequestParams) (*WalkthroughRequest, error) {
	row := q.db.QueryRow(ctx, createWalkthroughRequest,
		arg.Name,
		arg.WorkEmail,
		arg.Organization,
		arg.Role,
		arg.Interest,
		arg.Note,
		arg.RequestedDate,
		arg.RequestedTime,
		arg.DurationMinutes,
	)
	var i WalkthroughRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkEmail,
		&i.Organization,
		&i.Role,
		&i.Interest,
		&i.Note,
		&i.RequestedDate,
		&i.RequestedTime,
		&i.DurationMinutes,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}
